// seeders/materiaux-construction.js
const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

// Fonction pour générer un SKU
function generateSKU(name, category) {
  const prefix = category.substring(0, 3).toUpperCase();
  const nameCode = name.substring(0, 3).toUpperCase();
  const random = Math.floor(Math.random() * 1000)
    .toString()
    .padStart(3, "0");
  return `${prefix}-${nameCode}-${random}`;
}

// Fonction pour générer un code-barres
function generateBarcode() {
  return (
    "4" +
    Math.floor(Math.random() * 1000000000000)
      .toString()
      .padStart(12, "0")
  );
}

// Données de produits pour matériaux de construction et autres produits
const materiauxConstructionProducts = [
  // ======================
  // MATÉRIAUX DE CONSTRUCTION
  // ======================
  {
    name: "Ciment Portland 32.5R 25kg",
    description:
      "Ciment Portland pour tous travaux de maçonnerie, béton et mortier.",
    category: "Matériaux de Construction",
    subcategory: "Ciment & Mortier",
    price: 8.9,
    comparePrice: 9.8,
    cost: 5.2,
    sku: "CIM-PORT-325-25KG",
    barcode: "4000000001001",
    trackQuantity: true,
    quantity: 150,
    lowStock: 20,
    weight: 25,
    dimensions: { length: 40, width: 30, height: 15 },
    images: [
      "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop&q=60",
    ],
    status: "active",
    featured: true,
    visibility: "public",
    seoTitle: "Ciment Portland 32.5R 25kg - Matériaux Construction",
    seoDescription: "Ciment Portland 32.5R pour travaux de maçonnerie et béton",
    productType: "materiaux",
    foodCategory: null,
    isPerishable: false,
    expiryDate: null,
    storageTips: "Conserver au sec à l'abri de l'humidité",
    nutritionalInfo: null,
    allergens: [],
    isOrganic: false,
    origin: "France",
    brand: "Cimenterie Nationale",
    unit: "sac",
    isVegan: null,
    isVegetarian: null,
    healthScore: null,
  },
  {
    name: "Parpaings Creux 20x20x50",
    description:
      "Parpaings creux pour construction de murs porteurs et cloisons.",
    category: "Matériaux de Construction",
    subcategory: "Agglomérés & Parpaings",
    price: 2.45,
    comparePrice: 2.8,
    cost: 1.2,
    sku: "PARP-CREUX-20x50",
    barcode: "4000000001002",
    trackQuantity: true,
    quantity: 500,
    lowStock: 50,
    weight: 15,
    dimensions: { length: 50, width: 20, height: 20 },
    images: [
      "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop&q=60",
    ],
    status: "active",
    featured: false,
    visibility: "public",
    seoTitle: "Parpaings Creux 20x20x50 - Construction Mur",
    seoDescription: "Parpaings creux pour murs porteurs et cloisons",
    productType: "materiaux",
    foodCategory: null,
    isPerishable: false,
    expiryDate: null,
    storageTips: "Stockage à plat sur sol propre",
    nutritionalInfo: null,
    allergens: [],
    isOrganic: false,
    origin: "France",
    brand: "Matériaux & Co",
    unit: "pièce",
    isVegan: null,
    isVegetarian: null,
    healthScore: null,
  },
  {
    name: "Brique de Terre Cuite",
    description: "Briques de terre cuite pour construction traditionnelle.",
    category: "Matériaux de Construction",
    subcategory: "Briques",
    price: 1.2,
    comparePrice: 1.4,
    cost: 0.65,
    sku: "BRIQ-TERRE-CUITE",
    barcode: "4000000001003",
    trackQuantity: true,
    quantity: 800,
    lowStock: 100,
    weight: 2.5,
    dimensions: { length: 22, width: 10.5, height: 6.5 },
    images: [
      "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop&q=60",
    ],
    status: "active",
    featured: false,
    visibility: "public",
    seoTitle: "Brique Terre Cuite - Construction Traditionnelle",
    seoDescription: "Briques de terre cuite pour maçonnerie traditionnelle",
    productType: "materiaux",
    foodCategory: null,
    isPerishable: false,
    expiryDate: null,
    storageTips: "Protéger de l'humidité",
    nutritionalInfo: null,
    allergens: [],
    isOrganic: false,
    origin: "France",
    brand: "Tuilerie Tradition",
    unit: "pièce",
    isVegan: null,
    isVegetarian: null,
    healthScore: null,
  },
  {
    name: "Lambris Chêne Massif",
    description: "Lambris en chêne massif pour décoration intérieure murale.",
    category: "Bois & Dérivés",
    subcategory: "Lambris & Panneaux",
    price: 28.9,
    comparePrice: 32.5,
    cost: 16.8,
    sku: "LAMB-CHENE-MASSIF",
    barcode: "4000000001004",
    trackQuantity: true,
    quantity: 120,
    lowStock: 15,
    weight: 8,
    dimensions: { length: 200, width: 15, height: 2 },
    images: [
      "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop&q=60",
    ],
    status: "active",
    featured: true,
    visibility: "public",
    seoTitle: "Lambris Chêne Massif - Décoration Murale",
    seoDescription: "Lambris en chêne massif pour décoration intérieure",
    productType: "materiaux",
    foodCategory: null,
    isPerishable: false,
    expiryDate: null,
    storageTips: "Conserver à l'abri de l'humidité",
    nutritionalInfo: null,
    allergens: [],
    isOrganic: false,
    origin: "France",
    brand: "Bois Noble",
    unit: "mètre linéaire",
    isVegan: null,
    isVegetarian: null,
    healthScore: null,
  },
  {
    name: "Planche de Sapin 200x15x2 cm",
    description: "Planche de sapin rabotée pour menuiserie et bricolage.",
    category: "Bois & Dérivés",
    subcategory: "Planches & Madriers",
    price: 12.5,
    comparePrice: 14.2,
    cost: 7.8,
    sku: "PLAN-SAPIN-200CM",
    barcode: "4000000001005",
    trackQuantity: true,
    quantity: 200,
    lowStock: 25,
    weight: 3.5,
    dimensions: { length: 200, width: 15, height: 2 },
    images: [
      "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop&q=60",
    ],
    status: "active",
    featured: false,
    visibility: "public",
    seoTitle: "Planche Sapin 200cm - Menuiserie Bricolage",
    seoDescription: "Planche de sapin rabotée pour travaux de menuiserie",
    productType: "materiaux",
    foodCategory: null,
    isPerishable: false,
    expiryDate: null,
    storageTips: "Stockage à plat",
    nutritionalInfo: null,
    allergens: [],
    isOrganic: false,
    origin: "France",
    brand: "Scierie du Nord",
    unit: "pièce",
    isVegan: null,
    isVegetarian: null,
    healthScore: null,
  },
  {
    name: "Panneau MDF 244x122x18 mm",
    description: "Panneau MDF pour ameublement et agencement intérieur.",
    category: "Bois & Dérivés",
    subcategory: "Panneaux Décoratifs",
    price: 42.9,
    comparePrice: 48.5,
    cost: 26.4,
    sku: "PAN-MDF-244x122",
    barcode: "4000000001006",
    trackQuantity: true,
    quantity: 80,
    lowStock: 10,
    weight: 35,
    dimensions: { length: 244, width: 122, height: 1.8 },
    images: [
      "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop&q=60",
    ],
    status: "active",
    featured: true,
    visibility: "public",
    seoTitle: "Panneau MDF 244x122x18 - Aménagement Intérieur",
    seoDescription: "Panneau MDF pour ameublement et agencement",
    productType: "materiaux",
    foodCategory: null,
    isPerishable: false,
    expiryDate: null,
    storageTips: "Stockage à plat sur sol plan",
    nutritionalInfo: null,
    allergens: [],
    isOrganic: false,
    origin: "France",
    brand: "Panel Industries",
    unit: "panneau",
    isVegan: null,
    isVegetarian: null,
    healthScore: null,
  },
  {
    name: "Carrelage Céramique 30x30 cm",
    description:
      "Carrelage céramique pour sol et mur, aspect pierre naturelle.",
    category: "Carrelage & Faïence",
    subcategory: "Carrelage Sol",
    price: 18.9,
    comparePrice: 22.5,
    cost: 11.2,
    sku: "CAR-CER-30x30",
    barcode: "4000000001007",
    trackQuantity: true,
    quantity: 300,
    lowStock: 30,
    weight: 25,
    dimensions: { length: 30, width: 30, height: 0.8 },
    images: [
      "https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=500&auto=format&fit=crop&q=60",
    ],
    status: "active",
    featured: true,
    visibility: "public",
    seoTitle: "Carrelage Céramique 30x30 - Sol & Mur",
    seoDescription: "Carrelage céramique aspect pierre naturelle",
    productType: "materiaux",
    foodCategory: null,
    isPerishable: false,
    expiryDate: null,
    storageTips: "Stockage vertical protégé",
    nutritionalInfo: null,
    allergens: [],
    isOrganic: false,
    origin: "Italie",
    brand: "Ceramica Italia",
    unit: "m²",
    isVegan: null,
    isVegetarian: null,
    healthScore: null,
  },
  {
    name: "Mosaïque Verre Murale",
    description:
      "Mosaïque en verre pour décoration murale salle de bain et cuisine.",
    category: "Carrelage & Faïence",
    subcategory: "Mosaïques",
    price: 65.9,
    comparePrice: 75.0,
    cost: 38.5,
    sku: "MOS-VERR-MURALE",
    barcode: "4000000001008",
    trackQuantity: true,
    quantity: 60,
    lowStock: 8,
    weight: 15,
    dimensions: { length: 30, width: 30, height: 0.5 },
    images: [
      "https://images.unsplash.com/photo-1507652313519-d4e9174996dd?w=500&auto=format&fit=crop&q=60",
    ],
    status: "active",
    featured: false,
    visibility: "public",
    seoTitle: "Mosaïque Verre Murale - Décoration Salle de Bain",
    seoDescription: "Mosaïque en verre pour décoration murale intérieure",
    productType: "materiaux",
    foodCategory: null,
    isPerishable: false,
    expiryDate: null,
    storageTips: "Protéger des chocs",
    nutritionalInfo: null,
    allergens: [],
    isOrganic: false,
    origin: "Italie",
    brand: "Vetreria Artistica",
    unit: "m²",
    isVegan: null,
    isVegetarian: null,
    healthScore: null,
  },
  {
    name: "Peinture Murale Blanche Mate 5L",
    description: "Peinture acrylique mate blanche pour murs intérieurs.",
    category: "Peinture & Enduits",
    subcategory: "Peintures Intérieures",
    price: 48.9,
    comparePrice: 55.0,
    cost: 28.5,
    sku: "PEINT-BLAN-MATE-5L",
    barcode: "4000000001009",
    trackQuantity: true,
    quantity: 120,
    lowStock: 15,
    weight: 6.5,
    dimensions: { length: 20, width: 20, height: 28 },
    images: [
      "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?w=500&auto=format&fit=crop&q=60",
    ],
    status: "active",
    featured: true,
    visibility: "public",
    seoTitle: "Peinture Murale Blanche Mate 5L - Intérieur",
    seoDescription: "Peinture acrylique mate pour murs intérieurs",
    productType: "materiaux",
    foodCategory: null,
    isPerishable: true,
    expiryDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
    storageTips: "Conserver à l'abri du gel",
    nutritionalInfo: null,
    allergens: [],
    isOrganic: false,
    origin: "France",
    brand: "Peintures Pro",
    unit: "pot",
    isVegan: null,
    isVegetarian: null,
    healthScore: null,
  },
  {
    name: "Enduit de Lissage 25kg",
    description:
      "Enduit de lissage fin pour préparation des supports avant peinture.",
    category: "Peinture & Enduits",
    subcategory: "Enduits & Primes",
    price: 16.9,
    comparePrice: 19.5,
    cost: 9.8,
    sku: "END-LISSAGE-25KG",
    barcode: "4000000001010",
    trackQuantity: true,
    quantity: 180,
    lowStock: 20,
    weight: 25,
    dimensions: { length: 40, width: 30, height: 15 },
    images: [
      "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?w=500&auto=format&fit=crop&q=60",
    ],
    status: "active",
    featured: false,
    visibility: "public",
    seoTitle: "Enduit de Lissage 25kg - Préparation Mur",
    seoDescription: "Enduit fin pour lissage des supports avant peinture",
    productType: "materiaux",
    foodCategory: null,
    isPerishable: false,
    expiryDate: null,
    storageTips: "Conserver au sec",
    nutritionalInfo: null,
    allergens: [],
    isOrganic: false,
    origin: "France",
    brand: "Enduits Pro",
    unit: "sac",
    isVegan: null,
    isVegetarian: null,
    healthScore: null,
  },
  {
    name: "Tuyau PVC Égout 100mm",
    description: "Tuyau PVC pour évacuation des eaux usées et eaux pluviales.",
    category: "Plomberie",
    subcategory: "Tuyaux & Raccords",
    price: 14.9,
    comparePrice: 16.8,
    cost: 8.5,
    sku: "TUY-PVC-100-EGOUT",
    barcode: "4000000001011",
    trackQuantity: true,
    quantity: 250,
    lowStock: 25,
    weight: 3.5,
    dimensions: { length: 200, width: 11, height: 11 },
    images: [
      "https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=500&auto=format&fit=crop&q=60",
    ],
    status: "active",
    featured: false,
    visibility: "public",
    seoTitle: "Tuyau PVC Égout 100mm - Évacuation Eaux",
    seoDescription: "Tuyau PVC pour évacuation eaux usées et pluviales",
    productType: "materiaux",
    foodCategory: null,
    isPerishable: false,
    expiryDate: null,
    storageTips: "Stockage à plat",
    nutritionalInfo: null,
    allergens: [],
    isOrganic: false,
    origin: "France",
    brand: "Plomberie Expert",
    unit: "mètre linéaire",
    isVegan: null,
    isVegetarian: null,
    healthScore: null,
  },
  {
    name: "Robinet de Lavabo Chromé",
    description: "Robinet mélangeur chromé pour lavabo de salle de bain.",
    category: "Plomberie",
    subcategory: "Robinetterie",
    price: 89.9,
    comparePrice: 105.0,
    cost: 52.8,
    sku: "ROB-LAVABO-CHROME",
    barcode: "4000000001012",
    trackQuantity: true,
    quantity: 85,
    lowStock: 10,
    weight: 2.8,
    dimensions: { length: 25, width: 15, height: 10 },
    images: [
      "https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=500&auto=format&fit=crop&q=60",
    ],
    status: "active",
    featured: true,
    visibility: "public",
    seoTitle: "Robinet Lavabo Chromé - Robinetterie Salle de Bain",
    seoDescription: "Robinet mélangeur chromé pour lavabo",
    productType: "materiaux",
    foodCategory: null,
    isPerishable: false,
    expiryDate: null,
    storageTips: "Conserver dans son emballage",
    nutritionalInfo: null,
    allergens: [],
    isOrganic: false,
    origin: "Allemagne",
    brand: "Grohe",
    unit: "pièce",
    isVegan: null,
    isVegetarian: null,
    healthScore: null,
  },
  {
    name: "Câble Électrique H07V-U 2.5mm²",
    description:
      "Câble électrique rigide monoconducteur pour installation fixe.",
    category: "Électricité",
    subcategory: "Câbles & Fils",
    price: 1.45,
    comparePrice: 1.65,
    cost: 0.85,
    sku: "CAB-H07V-2.5MM",
    barcode: "4000000001013",
    trackQuantity: true,
    quantity: 500,
    lowStock: 50,
    weight: 0.3,
    dimensions: { length: 100, width: 5, height: 5 },
    images: [
      "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=500&auto=format&fit=crop&q=60",
    ],
    status: "active",
    featured: false,
    visibility: "public",
    seoTitle: "Câble Électrique H07V-U 2.5mm² - Installation Fixe",
    seoDescription: "Câble électrique rigide pour installation électrique",
    productType: "materiaux",
    foodCategory: null,
    isPerishable: false,
    expiryDate: null,
    storageTips: "Rouler les surplus",
    nutritionalInfo: null,
    allergens: [],
    isOrganic: false,
    origin: "France",
    brand: "Câblerie Française",
    unit: "mètre",
    isVegan: null,
    isVegetarian: null,
    healthScore: null,
  },
  {
    name: "Tableau Électrique 12 Modules",
    description:
      "Tableau électrique encastrable 12 modules avec peigne de raccordement.",
    category: "Électricité",
    subcategory: "Tableaux & Disjoncteurs",
    price: 89.9,
    comparePrice: 105.0,
    cost: 55.2,
    sku: "TAB-ELEC-12MOD",
    barcode: "4000000001014",
    trackQuantity: true,
    quantity: 75,
    lowStock: 8,
    weight: 4.2,
    dimensions: { length: 35, width: 25, height: 12 },
    images: [
      "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=500&auto=format&fit=crop&q=60",
    ],
    status: "active",
    featured: true,
    visibility: "public",
    seoTitle: "Tableau Électrique 12 Modules - Distribution Électrique",
    seoDescription: "Tableau électrique encastrable avec peigne",
    productType: "materiaux",
    foodCategory: null,
    isPerishable: false,
    expiryDate: null,
    storageTips: "Conserver dans son emballage",
    nutritionalInfo: null,
    allergens: [],
    isOrganic: false,
    origin: "France",
    brand: "Schneider Electric",
    unit: "pièce",
    isVegan: null,
    isVegetarian: null,
    healthScore: null,
  },
  {
    name: "Laine de Verre 100mm R=2.5",
    description: "Isolant thermique et acoustique en laine de verre.",
    category: "Isolation",
    subcategory: "Isolants Thermiques",
    price: 8.9,
    comparePrice: 10.2,
    cost: 5.4,
    sku: "LAINE-VERR-100MM",
    barcode: "4000000001015",
    trackQuantity: true,
    quantity: 200,
    lowStock: 20,
    weight: 1.2,
    dimensions: { length: 120, width: 60, height: 10 },
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&auto=format&fit=crop&q=60",
    ],
    status: "active",
    featured: true,
    visibility: "public",
    seoTitle: "Laine de Verre 100mm - Isolation Thermique",
    seoDescription: "Isolant en laine de verre pour murs et combles",
    productType: "materiaux",
    foodCategory: null,
    isPerishable: false,
    expiryDate: null,
    storageTips: "Protéger de l'humidité",
    nutritionalInfo: null,
    allergens: [],
    isOrganic: false,
    origin: "France",
    brand: "Isover",
    unit: "m²",
    isVegan: null,
    isVegetarian: null,
    healthScore: null,
  },
  {
    name: "Pare-Vapeur Anti-Humidité",
    description: "Film pare-vapeur pour isolation des combles et murs.",
    category: "Isolation",
    subcategory: "Accessoires Isolation",
    price: 3.2,
    comparePrice: 3.8,
    cost: 1.9,
    sku: "PARE-VAPEUR-ISO",
    barcode: "4000000001016",
    trackQuantity: true,
    quantity: 300,
    lowStock: 30,
    weight: 0.8,
    dimensions: { length: 50, width: 1.5, height: 5 },
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&auto=format&fit=crop&q=60",
    ],
    status: "active",
    featured: false,
    visibility: "public",
    seoTitle: "Pare-Vapeur Anti-Humidité - Isolation Combles",
    seoDescription: "Film pare-vapeur pour protection contre l'humidité",
    productType: "materiaux",
    foodCategory: null,
    isPerishable: false,
    expiryDate: null,
    storageTips: "Rouler après utilisation",
    nutritionalInfo: null,
    allergens: [],
    isOrganic: false,
    origin: "France",
    brand: "Iso Protect",
    unit: "mètre linéaire",
    isVegan: null,
    isVegetarian: null,
    healthScore: null,
  },
  // ======================
  // OUTILLAGE & ÉQUIPEMENT
  // ======================
  {
    name: "Perceuse Visseuse Sans Fil 18V",
    description:
      "Perceuse-visseuse sans fil avec 2 batteries et chargeur rapide.",
    category: "Outillage",
    subcategory: "Outils Électroportatifs",
    price: 189.9,
    comparePrice: 225.0,
    cost: 115.8,
    sku: "PERC-VIS-18V",
    barcode: "4000000001017",
    trackQuantity: true,
    quantity: 45,
    lowStock: 5,
    weight: 2.8,
    dimensions: { length: 30, width: 20, height: 15 },
    images: [
      "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop&q=60",
    ],
    status: "active",
    featured: true,
    visibility: "public",
    seoTitle: "Perceuse Visseuse 18V Sans Fil - Outillage Professionnel",
    seoDescription: "Perceuse-visseuse sans fil avec batteries incluses",
    productType: "materiaux",
    foodCategory: null,
    isPerishable: false,
    expiryDate: null,
    storageTips: "Recharger les batteries régulièrement",
    nutritionalInfo: null,
    allergens: [],
    isOrganic: false,
    origin: "Allemagne",
    brand: "Bosch Professional",
    unit: "kit",
    isVegan: null,
    isVegetarian: null,
    healthScore: null,
  },
  {
    name: "Marteau de Charpentier 500g",
    description: "Marteau de charpentier avec manche en frêne et tête forgée.",
    category: "Outillage",
    subcategory: "Outils à Main",
    price: 24.9,
    comparePrice: 28.5,
    cost: 14.8,
    sku: "MART-CHARP-500G",
    barcode: "4000000001018",
    trackQuantity: true,
    quantity: 120,
    lowStock: 15,
    weight: 0.65,
    dimensions: { length: 35, width: 15, height: 5 },
    images: [
      "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop&q=60",
    ],
    status: "active",
    featured: false,
    visibility: "public",
    seoTitle: "Marteau de Charpentier 500g - Outil à Main",
    seoDescription: "Marteau de charpentier avec manche en frêne",
    productType: "materiaux",
    foodCategory: null,
    isPerishable: false,
    expiryDate: null,
    storageTips: "Nettoyer après utilisation",
    nutritionalInfo: null,
    allergens: [],
    isOrganic: false,
    origin: "France",
    brand: "Facom",
    unit: "pièce",
    isVegan: null,
    isVegetarian: null,
    healthScore: null,
  },
  {
    name: "Scie Circulaire 1400W",
    description: "Scie circulaire puissante avec guide parallèle et mallette.",
    category: "Outillage",
    subcategory: "Scies & Découpe",
    price: 159.9,
    comparePrice: 185.0,
    cost: 95.4,
    sku: "SCI-CIRC-1400W",
    barcode: "4000000001019",
    trackQuantity: true,
    quantity: 30,
    lowStock: 3,
    weight: 5.2,
    dimensions: { length: 45, width: 35, height: 25 },
    images: [
      "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop&q=60",
    ],
    status: "active",
    featured: true,
    visibility: "public",
    seoTitle: "Scie Circulaire 1400W - Découpe Bois & Matériaux",
    seoDescription: "Scie circulaire professionnelle avec guide parallèle",
    productType: "materiaux",
    foodCategory: null,
    isPerishable: false,
    expiryDate: null,
    storageTips: "Nettoyer la lame après utilisation",
    nutritionalInfo: null,
    allergens: [],
    isOrganic: false,
    origin: "Allemagne",
    brand: "Makita",
    unit: "pièce",
    isVegan: null,
    isVegetarian: null,
    healthScore: null,
  },
  {
    name: "Niveau Laser Auto-Nivelant",
    description:
      "Niveau laser rotatif auto-nivelant pour travaux de précision.",
    category: "Outillage",
    subcategory: "Mesure & Niveau",
    price: 289.9,
    comparePrice: 345.0,
    cost: 178.5,
    sku: "NIV-LASER-AUTO",
    barcode: "4000000001020",
    trackQuantity: true,
    quantity: 25,
    lowStock: 3,
    weight: 2.5,
    dimensions: { length: 20, width: 15, height: 15 },
    images: [
      "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop&q=60",
    ],
    status: "active",
    featured: true,
    visibility: "public",
    seoTitle: "Niveau Laser Auto-Nivelant - Précision Travaux",
    seoDescription: "Niveau laser rotatif pour alignement précis",
    productType: "materiaux",
    foodCategory: null,
    isPerishable: false,
    expiryDate: null,
    storageTips: "Ranger dans son étui de protection",
    nutritionalInfo: null,
    allergens: [],
    isOrganic: false,
    origin: "Suisse",
    brand: "Leica",
    unit: "kit",
    isVegan: null,
    isVegetarian: null,
    healthScore: null,
  },
  // ======================
  // QUINCAILLERIE & FIXATIONS
  // ======================
  {
    name: "Vis à Bois BTR 4x60mm - 200pcs",
    description: "Vis à bois tête ronde laitonné, boîte de 200 pièces.",
    category: "Quincaillerie",
    subcategory: "Vis & Boulons",
    price: 8.9,
    comparePrice: 10.5,
    cost: 5.2,
    sku: "VIS-BOIS-4x60-200",
    barcode: "4000000001021",
    trackQuantity: true,
    quantity: 150,
    lowStock: 20,
    weight: 0.8,
    dimensions: { length: 15, width: 10, height: 5 },
    images: [
      "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop&q=60",
    ],
    status: "active",
    featured: false,
    visibility: "public",
    seoTitle: "Vis à Bois 4x60mm - 200 Pièces - Fixation Bois",
    seoDescription: "Vis à bois tête ronde pour assemblage menuiserie",
    productType: "materiaux",
    foodCategory: null,
    isPerishable: false,
    expiryDate: null,
    storageTips: "Conserver dans son emballage",
    nutritionalInfo: null,
    allergens: [],
    isOrganic: false,
    origin: "France",
    brand: "Vis et Fixations",
    unit: "boîte",
    isVegan: null,
    isVegetarian: null,
    healthScore: null,
  },
  {
    name: "Cheville Fischer S10 10x60mm - 100pcs",
    description: "Cheville universelle pour matériaux pleins, boîte de 100.",
    category: "Quincaillerie",
    subcategory: "Chevilles & Ancrages",
    price: 12.9,
    comparePrice: 14.8,
    cost: 7.5,
    sku: "CHEV-FISCHER-S10",
    barcode: "4000000001022",
    trackQuantity: true,
    quantity: 180,
    lowStock: 20,
    weight: 0.5,
    dimensions: { length: 15, width: 10, height: 5 },
    images: [
      "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop&q=60",
    ],
    status: "active",
    featured: false,
    visibility: "public",
    seoTitle: "Cheville Fischer S10 10x60mm - Fixation Mur",
    seoDescription: "Cheville universelle pour fixation murale",
    productType: "materiaux",
    foodCategory: null,
    isPerishable: false,
    expiryDate: null,
    storageTips: "Conserver à l'abri de l'humidité",
    nutritionalInfo: null,
    allergens: [],
    isOrganic: false,
    origin: "Allemagne",
    brand: "Fischer",
    unit: "boîte",
    isVegan: null,
    isVegetarian: null,
    healthScore: null,
  },
  {
    name: "Charnière Piano 100cm",
    description: "Charnière piano en acier inoxydable pour meubles et portes.",
    category: "Quincaillerie",
    subcategory: "Charnières & Paumelles",
    price: 15.9,
    comparePrice: 18.5,
    cost: 9.8,
    sku: "CHARN-PIANO-100CM",
    barcode: "4000000001023",
    trackQuantity: true,
    quantity: 85,
    lowStock: 10,
    weight: 1.2,
    dimensions: { length: 100, width: 3, height: 2 },
    images: [
      "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop&q=60",
    ],
    status: "active",
    featured: false,
    visibility: "public",
    seoTitle: "Charnière Piano 100cm - Meuble & Porte",
    seoDescription: "Charnière piano inox pour fixation meuble",
    productType: "materiaux",
    foodCategory: null,
    isPerishable: false,
    expiryDate: null,
    storageTips: "Protéger de l'oxydation",
    nutritionalInfo: null,
    allergens: [],
    isOrganic: false,
    origin: "France",
    brand: "Quincaillerie Pro",
    unit: "pièce",
    isVegan: null,
    isVegetarian: null,
    healthScore: null,
  },
  {
    name: "Serrure Encastrable 30/40mm",
    description: "Serrure encastrable pour porte intérieure avec 2 clés.",
    category: "Quincaillerie",
    subcategory: "Serrurerie",
    price: 28.9,
    comparePrice: 32.5,
    cost: 17.4,
    sku: "SERR-ENCAST-30/40",
    barcode: "4000000001024",
    trackQuantity: true,
    quantity: 65,
    lowStock: 8,
    weight: 1.5,
    dimensions: { length: 12, width: 8, height: 5 },
    images: [
      "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop&q=60",
    ],
    status: "active",
    featured: true,
    visibility: "public",
    seoTitle: "Serrure Encastrable 30/40mm - Porte Intérieure",
    seoDescription: "Serrure encastrable avec clés pour porte intérieure",
    productType: "materiaux",
    foodCategory: null,
    isPerishable: false,
    expiryDate: null,
    storageTips: "Graisser les mécanismes",
    nutritionalInfo: null,
    allergens: [],
    isOrganic: false,
    origin: "France",
    brand: "Vachette",
    unit: "pièce",
    isVegan: null,
    isVegetarian: null,
    healthScore: null,
  },
  // ======================
  // SÉCURITÉ & PROTECTION
  // ======================
  {
    name: "Casque de Sécurité avec Visière",
    description: "Casque de sécurité pour chantier avec visière de protection.",
    category: "Sécurité",
    subcategory: "Équipements de Protection",
    price: 24.9,
    comparePrice: 28.5,
    cost: 14.8,
    sku: "CASQUE-SECU-VISIERE",
    barcode: "4000000001025",
    trackQuantity: true,
    quantity: 95,
    lowStock: 10,
    weight: 0.8,
    dimensions: { length: 30, width: 25, height: 20 },
    images: [
      "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop&q=60",
    ],
    status: "active",
    featured: true,
    visibility: "public",
    seoTitle: "Casque de Sécurité avec Visière - Protection Chantier",
    seoDescription: "Casque de sécurité pour travaux et chantiers",
    productType: "materiaux",
    foodCategory: null,
    isPerishable: false,
    expiryDate: null,
    storageTips: "Nettoyer régulièrement",
    nutritionalInfo: null,
    allergens: [],
    isOrganic: false,
    origin: "France",
    brand: "Delta Plus",
    unit: "pièce",
    isVegan: null,
    isVegetarian: null,
    healthScore: null,
  },
  {
    name: "Gants de Travail Anti-Coupure",
    description: "Gants de protection anti-coupure pour travaux manuels.",
    category: "Sécurité",
    subcategory: "Protections des Mains",
    price: 18.9,
    comparePrice: 22.0,
    cost: 11.5,
    sku: "GANTS-ANTI-COUPURE",
    barcode: "4000000001026",
    trackQuantity: true,
    quantity: 150,
    lowStock: 20,
    weight: 0.3,
    dimensions: { length: 25, width: 15, height: 5 },
    images: [
      "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop&q=60",
    ],
    status: "active",
    featured: false,
    visibility: "public",
    seoTitle: "Gants de Travail Anti-Coupure - Protection Mains",
    seoDescription: "Gants de protection pour travaux manuels",
    productType: "materiaux",
    foodCategory: null,
    isPerishable: false,
    expiryDate: null,
    storageTips: "Laver à la main",
    nutritionalInfo: null,
    allergens: [],
    isOrganic: false,
    origin: "France",
    brand: "MAPA Professional",
    unit: "paire",
    isVegan: null,
    isVegetarian: null,
    healthScore: null,
  },
  {
    name: "Lunettes de Protection Anti-Rayures",
    description: "Lunettes de protection avec traitement anti-rayures.",
    category: "Sécurité",
    subcategory: "Protection des Yeux",
    price: 12.9,
    comparePrice: 15.0,
    cost: 7.8,
    sku: "LUNETTES-PROTECTION",
    barcode: "4000000001027",
    trackQuantity: true,
    quantity: 120,
    lowStock: 15,
    weight: 0.2,
    dimensions: { length: 20, width: 15, height: 5 },
    images: [
      "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop&q=60",
    ],
    status: "active",
    featured: false,
    visibility: "public",
    seoTitle: "Lunettes de Protection - Sécurité Chantier",
    seoDescription: "Lunettes de protection pour travaux",
    productType: "materiaux",
    foodCategory: null,
    isPerishable: false,
    expiryDate: null,
    storageTips: "Nettoyer avec un chiffon doux",
    nutritionalInfo: null,
    allergens: [],
    isOrganic: false,
    origin: "France",
    brand: "Bolle",
    unit: "paire",
    isVegan: null,
    isVegetarian: null,
    healthScore: null,
  },
  // ======================
  // AMÉNAGEMENT & DÉCORATION
  // ======================
  {
    name: "Parquet Flottant Chêne 10mm",
    description: "Parquet flottant chêne massif pour sol intérieur.",
    category: "Sol & Revêtement",
    subcategory: "Parquets",
    price: 32.9,
    comparePrice: 38.5,
    cost: 20.8,
    sku: "PARQ-FLOTT-CHE-NE",
    barcode: "4000000001028",
    trackQuantity: true,
    quantity: 180,
    lowStock: 20,
    weight: 15,
    dimensions: { length: 120, width: 20, height: 1 },
    images: [
      "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop&q=60",
    ],
    status: "active",
    featured: true,
    visibility: "public",
    seoTitle: "Parquet Flottant Chêne 10mm - Sol Intérieur",
    seoDescription: "Parquet flottant en chêne massif",
    productType: "materiaux",
    foodCategory: null,
    isPerishable: false,
    expiryDate: null,
    storageTips: "Acclimater 48h avant pose",
    nutritionalInfo: null,
    allergens: [],
    isOrganic: false,
    origin: "France",
    brand: "Tarkett",
    unit: "m²",
    isVegan: null,
    isVegetarian: null,
    healthScore: null,
  },
  {
    name: "Papier Peint Intissé Uni",
    description: "Papier peint intissé uni pour décoration murale.",
    category: "Décoration",
    subcategory: "Papiers Peints",
    price: 18.9,
    comparePrice: 22.0,
    cost: 11.5,
    sku: "PAP-PEINT-INTISSE",
    barcode: "4000000001029",
    trackQuantity: true,
    quantity: 150,
    lowStock: 15,
    weight: 2.5,
    dimensions: { length: 100, width: 0.53, height: 5 },
    images: [
      "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop&q=60",
    ],
    status: "active",
    featured: false,
    visibility: "public",
    seoTitle: "Papier Peint Intissé Uni - Décoration Mur",
    seoDescription: "Papier peint intissé pour murs intérieurs",
    productType: "materiaux",
    foodCategory: null,
    isPerishable: false,
    expiryDate: null,
    storageTips: "Conserver à plat",
    nutritionalInfo: null,
    allergens: [],
    isOrganic: false,
    origin: "France",
    brand: "Graham & Brown",
    unit: "rouleau",
    isVegan: null,
    isVegetarian: null,
    healthScore: null,
  },
  {
    name: "Moulure Cornière PVC Blanc",
    description:
      "Moulure cornière en PVC pour protection et décoration des angles.",
    category: "Décoration",
    subcategory: "Moulures & Plinthes",
    price: 4.9,
    comparePrice: 5.8,
    cost: 2.9,
    sku: "MOUL-CORNIERE-PVC",
    barcode: "4000000001030",
    trackQuantity: true,
    quantity: 250,
    lowStock: 25,
    weight: 0.5,
    dimensions: { length: 200, width: 3, height: 3 },
    images: [
      "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop&q=60",
    ],
    status: "active",
    featured: false,
    visibility: "public",
    seoTitle: "Moulure Cornière PVC Blanc - Protection Angle",
    seoDescription: "Moulure cornière en PVC pour angles muraux",
    productType: "materiaux",
    foodCategory: null,
    isPerishable: false,
    expiryDate: null,
    storageTips: "Couper avec scie à métaux",
    nutritionalInfo: null,
    allergens: [],
    isOrganic: false,
    origin: "France",
    brand: "Placo",
    unit: "mètre linéaire",
    isVegan: null,
    isVegetarian: null,
    healthScore: null,
  },
];

// Fonction pour générer un slug à partir du nom
function generateSlug(name) {
  return name
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)+/g, "")
    .substring(0, 100);
}

async function main() {
  console.log(
    "🌱 Début du seeding des matériaux de construction et autres produits..."
  );
  try {
    // Récupérer l'utilisateur spécifique par email
    const specificUser = await prisma.user.findUnique({
      where: { email: "pro@servo.mg" },
      select: { id: true },
    });

    if (!specificUser) {
      console.log(
        "❌ Utilisateur avec email pro@servo.mg non trouvé dans la base de données"
      );
      console.log("💡 Veuillez créer cet utilisateur avant de lancer ce seed");
      return;
    }

    console.log(`👤 Utilisateur trouvé: ${specificUser.id}`);

    // Vérifier s'il y a déjà des produits matériaux
    const existingProducts = await prisma.product.count({
      where: {
        productType: "materiaux",
      },
    });

    if (existingProducts > 0) {
      console.log(
        `⚠️ ${existingProducts} produits matériaux existants détectés`
      );
      console.log("🗑️ Suppression des anciens produits matériaux...");
      await prisma.product.deleteMany({
        where: {
          productType: "materiaux",
        },
      });
      console.log("✅ Anciens produits matériaux supprimés");
    }

    // Créer les produits matériaux
    console.log(
      `🛍️ Création de ${materiauxConstructionProducts.length} produits matériaux...`
    );
    for (const productData of materiauxConstructionProducts) {
      // Générer le slug
      const slug = generateSlug(productData.name);

      await prisma.product.create({
        data: {
          ...productData,
          slug,
          userId: specificUser.id,
          publishedAt: productData.status === "active" ? new Date() : null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      });
      console.log(`✅ Produit créé: ${productData.name}`);
    }

    console.log(
      "🎉 Seeding des matériaux de construction terminé avec succès!"
    );
    console.log(`📊 ${materiauxConstructionProducts.length} produits créés`);

    // Afficher un résumé par catégorie
    const productsByCategory = await prisma.product.groupBy({
      by: ["category"],
      where: {
        productType: "materiaux",
      },
      _count: {
        id: true,
      },
      orderBy: {
        category: "asc",
      },
    });
    console.log("\n📈 Résumé par catégorie:");
    productsByCategory.forEach((cat) => {
      console.log(` ${cat.category}: ${cat._count.id} produits`);
    });

    // Résumé par type de produit
    const productsByType = await prisma.product.groupBy({
      by: ["productType"],
      where: {
        productType: "materiaux",
      },
      _count: {
        id: true,
      },
      orderBy: {
        productType: "asc",
      },
    });
    console.log("\n🏷️ Résumé par type de produit:");
    productsByType.forEach((type) => {
      console.log(` ${type.productType}: ${type._count.id} produits`);
    });

    // Résumé par sous-catégorie
    const productsBySubcategory = await prisma.product.groupBy({
      by: ["subcategory"],
      where: {
        productType: "materiaux",
      },
      _count: {
        id: true,
      },
      orderBy: {
        subcategory: "asc",
      },
    });
    console.log("\n🗂️ Top 10 sous-catégories:");
    productsBySubcategory.slice(0, 10).forEach((sub) => {
      console.log(` ${sub.subcategory}: ${sub._count.id} produits`);
    });

    // Statistiques générales
    const totalProducts = await prisma.product.count({
      where: {
        productType: "materiaux",
      },
    });
    const featuredProducts = await prisma.product.count({
      where: {
        productType: "materiaux",
        featured: true,
      },
    });
    console.log("\n📊 Statistiques générales:");
    console.log(` Total produits: ${totalProducts}`);
    console.log(` Produits en vedette: ${featuredProducts}`);
    console.log(` Prix moyen: Calculé dans la base`);
  } catch (error) {
    console.error(
      "❌ Erreur lors du seeding des matériaux de construction:",
      error
    );
    throw error;
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
