// seeders/foodProducts.js
const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();

// Fonction pour générer des dates d'expiration
function getExpiryDate(daysFromNow) {
  return new Date(Date.now() + daysFromNow * 24 * 60 * 60 * 1000);
}

// Fonction pour générer un SKU
function generateSKU(name, category) {
  const prefix = category.substring(0, 3).toUpperCase();
  const nameCode = name.substring(0, 3).toUpperCase();
  const random = Math.floor(Math.random() * 1000).toString().padStart(3, '0');
  return `${prefix}-${nameCode}-${random}`;
}

// Fonction pour générer un code-barres
function generateBarcode() {
  return '2' + Math.floor(Math.random() * 1000000000000).toString().padStart(12, '0');
}

// Données de produits alimentaires organisées par les 4 sections avec foodCategory
const foodProductsData = [
  // ======================
  // COURS & EPICERIE
  // ======================
  {
    name: "Pommes Golden Bio",
    description: "Pommes Golden biologiques, croquantes et sucrées. Cultivées en France sans pesticides.",
    category: "Fruits Frais",
    subcategory: "Pommes",
    price: 3.5,
    comparePrice: 4.2,
    cost: 2.1,
    sku: "POMME-GOLD-BIO-001",
    barcode: "1234567891001",
    trackQuantity: true,
    quantity: 150,
    lowStock: 20,
    weight: 1.0,
    dimensions: { length: 30, width: 20, height: 15 },
    images: ["https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=500&auto=format&fit=crop&q=60"],
    status: "active",
    featured: true,
    visibility: "public",
    seoTitle: "Pommes Golden Bio - Agriculture Biologique",
    seoDescription: "Pommes Golden biologiques françaises, croquantes et sucrées",
    productType: "food",
    foodCategory: "fruits",
    isPerishable: true,
    expiryDate: getExpiryDate(14),
    storageTips: "Conserver au frais et à l'abri de la lumière",
    nutritionalInfo: { calories: 52, proteins: 0.3, carbs: 14, fats: 0.2, fiber: 2.4, sugar: 10 },
    allergens: [],
    isOrganic: true,
    origin: "France",
    brand: "Fermes Bio de France",
    unit: "kg",
    // Nouveaux champs
    isVegan: true,
    isVegetarian: true,
    healthScore: 9,
  },
  {
    name: "Fraises Gariguette",
    description: "Fraises Gariguette de saison, sucrées et parfumées. Récoltées à maturité.",
    category: "Fruits Frais",
    subcategory: "Fruits Rouges",
    price: 6.9,
    comparePrice: 7.5,
    cost: 4.2,
    sku: "FRAISE-GARIG-001",
    barcode: "1234567891002",
    trackQuantity: true,
    quantity: 80,
    lowStock: 15,
    weight: 0.5,
    dimensions: { length: 25, width: 15, height: 10 },
    images: ["https://images.unsplash.com/photo-1464454709131-ffd692591ee5?w=500&auto=format&fit=crop&q=60"],
    status: "active",
    featured: true,
    visibility: "public",
    seoTitle: "Fraises Gariguette Fraîches - Producteur Local",
    seoDescription: "Fraises Gariguette de saison, sucrées et parfumées",
    productType: "food",
    foodCategory: "fruits",
    isPerishable: true,
    expiryDate: getExpiryDate(3),
    storageTips: "Conserver au réfrigérateur et consommer rapidement",
    nutritionalInfo: { calories: 32, proteins: 0.7, carbs: 7.7, fats: 0.3, fiber: 2.0, vitaminC: 59 },
    allergens: [],
    isOrganic: false,
    origin: "Périgord, France",
    brand: "Verger du Sud-Ouest",
    unit: "barquette",
    // Nouveaux champs
    isVegan: true,
    isVegetarian: true,
    healthScore: 8,
  },
  {
    name: "Bananes Bio",
    description: "Bananes biologiques équitables, parfaitement mûres et savoureuses.",
    category: "Fruits Frais",
    subcategory: "Fruits Exotiques",
    price: 2.9,
    comparePrice: 3.4,
    cost: 1.6,
    sku: "BANANE-BIO-001",
    barcode: "1234567891003",
    trackQuantity: true,
    quantity: 200,
    lowStock: 30,
    weight: 1.0,
    dimensions: { length: 25, width: 15, height: 12 },
    images: ["https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=500&auto=format&fit=crop&q=60"],
    status: "active",
    featured: false,
    visibility: "public",
    seoTitle: "Bananes Bio Équitables - Agriculture Durable",
    seoDescription: "Bananes biologiques équitables, riches en potassium",
    productType: "food",
    foodCategory: "fruits",
    isPerishable: true,
    expiryDate: getExpiryDate(7),
    storageTips: "Conserver à température ambiante",
    nutritionalInfo: { calories: 89, proteins: 1.1, carbs: 23, fats: 0.3, fiber: 2.6, potassium: 358 },
    allergens: [],
    isOrganic: true,
    origin: "République Dominicaine",
    brand: "Bio Equitable",
    unit: "kg",
    // Nouveaux champs
    isVegan: true,
    isVegetarian: true,
    healthScore: 8,
  },
  {
    name: "Carottes Nouvelles Bio",
    description: "Carottes nouvelles biologiques, croquantes et sucrées. Récolte du jour.",
    category: "Légumes Frais",
    subcategory: "Légumes Racines",
    price: 2.8,
    comparePrice: 3.2,
    cost: 1.5,
    sku: "CAROTTE-NOUV-BIO-001",
    barcode: "1234567891004",
    trackQuantity: true,
    quantity: 200,
    lowStock: 30,
    weight: 1.0,
    dimensions: { length: 35, width: 20, height: 15 },
    images: ["https://images.unsplash.com/photo-1445282768818-728615cc910a?w=500&auto=format&fit=crop&q=60"],
    status: "active",
    featured: true,
    visibility: "public",
    seoTitle: "Carottes Nouvelles Bio - Agriculture Biologique",
    seoDescription: "Carottes nouvelles biologiques, croquantes et sucrées",
    productType: "food",
    foodCategory: "legumes",
    isPerishable: true,
    expiryDate: getExpiryDate(10),
    storageTips: "Conserver au frais et à l'abri de la lumière",
    nutritionalInfo: { calories: 41, proteins: 0.9, carbs: 10, fats: 0.2, fiber: 2.8, vitaminA: 16706 },
    allergens: [],
    isOrganic: true,
    origin: "Val de Loire, France",
    brand: "Jardins Bio de France",
    unit: "kg",
    // Nouveaux champs
    isVegan: true,
    isVegetarian: true,
    healthScore: 9,
  },
  {
    name: "Tomates Anciennes",
    description: "Tomates anciennes variétales, goût authentique et texture fondante.",
    category: "Légumes Frais",
    subcategory: "Tomates",
    price: 5.2,
    comparePrice: 6.0,
    cost: 3.1,
    sku: "TOMATE-ANCIEN-001",
    barcode: "1234567891005",
    trackQuantity: true,
    quantity: 120,
    lowStock: 20,
    weight: 0.8,
    dimensions: { length: 20, width: 15, height: 10 },
    images: ["https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500&auto=format&fit=crop&q=60"],
    status: "active",
    featured: false,
    visibility: "public",
    seoTitle: "Tomates Anciennes Variétales - Saveur Authentique",
    seoDescription: "Tomates anciennes aux saveurs intenses et texture fondante",
    productType: "food",
    foodCategory: "legumes",
    isPerishable: true,
    expiryDate: getExpiryDate(5),
    storageTips: "Conserver à température ambiante",
    nutritionalInfo: { calories: 18, proteins: 0.9, carbs: 3.9, fats: 0.2, fiber: 1.2, vitaminC: 14 },
    allergens: [],
    isOrganic: false,
    origin: "Provence, France",
    brand: "Jardins du Sud",
    unit: "kg",
    // Nouveaux champs
    isVegan: true,
    isVegetarian: true,
    healthScore: 8,
  },
  {
    name: "Lait Entier Bio 1L",
    description: "Lait entier biologique pasteurisé, riche en calcium et en goût.",
    category: "Produits Laitiers",
    subcategory: "Lait",
    price: 1.6,
    comparePrice: 1.8,
    cost: 0.9,
    sku: "LAIT-ENTIER-BIO-1L",
    barcode: "1234567891006",
    trackQuantity: true,
    quantity: 90,
    lowStock: 15,
    weight: 1.03,
    dimensions: { length: 8, width: 8, height: 20 },
    images: ["https://images.unsplash.com/photo-1563636619-e9143da7973b?w=500&auto=format&fit=crop&q=60"],
    status: "active",
    featured: true,
    visibility: "public",
    seoTitle: "Lait Entier Bio 1L - Riche en Calcium",
    seoDescription: "Lait entier biologique pasteurisé de qualité supérieure",
    productType: "food",
    foodCategory: "produits-laitiers",
    isPerishable: true,
    expiryDate: getExpiryDate(7),
    storageTips: "Conserver au réfrigérateur à 4°C",
    nutritionalInfo: { calories: 61, proteins: 3.2, carbs: 4.8, fats: 3.6, calcium: 120, vitaminD: 1.3 },
    allergens: ["lactose"],
    isOrganic: true,
    origin: "Normandie, France",
    brand: "Fermes Bio Normandes",
    unit: "litre",
    // Nouveaux champs
    isVegan: false,
    isVegetarian: true,
    healthScore: 7,
  },
  {
    name: "Yaourt Nature Bio",
    description: "Yaourt nature biologique crémeux, sans arômes ajoutés.",
    category: "Produits Laitiers",
    subcategory: "Yaourts",
    price: 0.8,
    comparePrice: 0.95,
    cost: 0.4,
    sku: "YAOURT-NATURE-BIO",
    barcode: "1234567891007",
    trackQuantity: true,
    quantity: 150,
    lowStock: 25,
    weight: 0.125,
    dimensions: { length: 6, width: 6, height: 5 },
    images: ["https://images.unsplash.com/photo-1567306300912-6e6a9c6c409e?w=500&auto=format&fit=crop&q=60"],
    status: "active",
    featured: false,
    visibility: "public",
    seoTitle: "Yaourt Nature Bio - Produit Laitier Biologique",
    seoDescription: "Yaourt nature biologique crémeux sans additifs",
    productType: "food",
    foodCategory: "produits-laitiers",
    isPerishable: true,
    expiryDate: getExpiryDate(21),
    storageTips: "Conserver au réfrigérateur",
    nutritionalInfo: { calories: 61, proteins: 3.5, carbs: 4.7, fats: 3.3, calcium: 121 },
    allergens: ["lactose"],
    isOrganic: true,
    origin: "Bretagne, France",
    brand: "Laiterie Bio",
    unit: "pièce",
    // Nouveaux champs
    isVegan: false,
    isVegetarian: true,
    healthScore: 6,
  },
  {
    name: "Oeufs Frais Bio x6",
    description: "Oeufs frais biologiques de poules élevées en plein air.",
    category: "Œufs",
    subcategory: "Œufs",
    price: 3.2,
    comparePrice: 3.6,
    cost: 1.8,
    sku: "OEUF-BIO-6P",
    barcode: "1234567891008",
    trackQuantity: true,
    quantity: 80,
    lowStock: 12,
    weight: 0.36,
    dimensions: { length: 15, width: 12, height: 8 },
    images: ["https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=500&auto=format&fit=crop&q=60"],
    status: "active",
    featured: true,
    visibility: "public",
    seoTitle: "Oeufs Frais Bio - Plein Air",
    seoDescription: "Oeufs frais biologiques de poules élevées en plein air",
    productType: "food",
    foodCategory: "oeufs",
    isPerishable: true,
    expiryDate: getExpiryDate(28),
    storageTips: "Conserver au réfrigérateur pointe en bas",
    nutritionalInfo: { calories: 155, proteins: 13, carbs: 1.1, fats: 11, cholesterol: 373 },
    allergens: ["oeuf"],
    isOrganic: true,
    origin: "Normandie, France",
    brand: "Fermes Bio",
    unit: "boite",
    // Nouveaux champs
    isVegan: false,
    isVegetarian: true,
    healthScore: 6,
  },
  {
    name: "Poulet Fermier Label Rouge",
    description: "Poulet fermier Label Rouge, chair ferme et goût authentique.",
    category: "Boucherie",
    subcategory: "Volaille",
    price: 12.9,
    comparePrice: 14.5,
    cost: 8.2,
    sku: "POULET-FERMIER-LR",
    barcode: "1234567891009",
    trackQuantity: true,
    quantity: 25,
    lowStock: 5,
    weight: 1.5,
    dimensions: { length: 25, width: 15, height: 10 },
    images: ["https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=500&auto=format&fit=crop&q=60"],
    status: "active",
    featured: true,
    visibility: "public",
    seoTitle: "Poulet Fermier Label Rouge - Qualité Supérieure",
    seoDescription: "Poulet fermier Label Rouge à la chair ferme et savoureuse",
    productType: "food",
    foodCategory: "viandes",
    isPerishable: true,
    expiryDate: getExpiryDate(3),
    storageTips: "Conserver au réfrigérateur et consommer rapidement",
    nutritionalInfo: { calories: 167, proteins: 20, carbs: 0, fats: 9, cholesterol: 76 },
    allergens: [],
    isOrganic: false,
    origin: "Bresse, France",
    brand: "Élevages de Bresse",
    unit: "pièce",
    // Nouveaux champs
    isVegan: false,
    isVegetarian: false,
    healthScore: 5,
  },
  {
    name: "Steak Haché 15% MG",
    description: "Steak haché pur bœuf à 15% de matière grasse, idéal pour les grillades.",
    category: "Boucherie",
    subcategory: "Viande Hachée",
    price: 8.9,
    comparePrice: 9.8,
    cost: 5.3,
    sku: "STEAK-HACHE-15MG",
    barcode: "1234567891010",
    trackQuantity: true,
    quantity: 40,
    lowStock: 8,
    weight: 0.5,
    dimensions: { length: 15, width: 10, height: 3 },
    images: ["https://images.unsplash.com/photo-1588347818122-c6f4d1c73a5e?w=500&auto=format&fit=crop&q=60"],
    status: "active",
    featured: false,
    visibility: "public",
    seoTitle: "Steak Haché 15% MG - Pur Bœuf",
    seoDescription: "Steak haché pur bœuf à 15% de matière grasse pour grillades",
    productType: "food",
    foodCategory: "viandes",
    isPerishable: true,
    expiryDate: getExpiryDate(2),
    storageTips: "Conserver au réfrigérateur et consommer sous 48h",
    nutritionalInfo: { calories: 212, proteins: 20, carbs: 0, fats: 14, iron: 2.1 },
    allergens: [],
    isOrganic: false,
    origin: "France",
    brand: "Boucherie Tradition",
    unit: "kg",
    // Nouveaux champs
    isVegan: false,
    isVegetarian: false,
    healthScore: 4,
  },
  {
    name: "Saumon Fumé Norvégien",
    description: "Saumon fumé norvégien de qualité supérieure, tranches épaisses.",
    category: "Poissonnerie",
    subcategory: "Poissons Fumés",
    price: 18.5,
    comparePrice: 21.0,
    cost: 11.8,
    sku: "SAUMON-FUME-NOR",
    barcode: "1234567891011",
    trackQuantity: true,
    quantity: 30,
    lowStock: 6,
    weight: 0.2,
    dimensions: { length: 20, width: 12, height: 4 },
    images: ["https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=500&auto=format&fit=crop&q=60"],
    status: "active",
    featured: true,
    visibility: "public",
    seoTitle: "Saumon Fumé Norvégien - Qualité Supérieure",
    seoDescription: "Saumon fumé norvégien aux tranches épaisses et savoureuses",
    productType: "food",
    foodCategory: "poissons",
    isPerishable: true,
    expiryDate: getExpiryDate(10),
    storageTips: "Conserver au réfrigérateur après ouverture",
    nutritionalInfo: { calories: 117, proteins: 18, carbs: 0, fats: 4.3, omega3: 2.1 },
    allergens: ["poisson"],
    isOrganic: false,
    origin: "Norvège",
    brand: "Fjord Norvégien",
    unit: "kg",
    // Nouveaux champs
    isVegan: false,
    isVegetarian: false,
    healthScore: 6,
  },
  {
    name: "Riz Basmati Bio 1kg",
    description: "Riz Basmati biologique de qualité supérieure, grains longs et parfumés.",
    category: "Épicerie Bio",
    subcategory: "Riz & Céréales",
    price: 4.9,
    comparePrice: 5.5,
    cost: 2.8,
    sku: "RIZ-BASMATI-BIO-1KG",
    barcode: "1234567891012",
    trackQuantity: true,
    quantity: 120,
    lowStock: 20,
    weight: 1.0,
    dimensions: { length: 20, width: 8, height: 15 },
    images: ["https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&auto=format&fit=crop&q=60"],
    status: "active",
    featured: true,
    visibility: "public",
    seoTitle: "Riz Basmati Bio 1kg - Qualité Supérieure",
    seoDescription: "Riz Basmati biologique aux grains longs et parfumés",
    productType: "food",
    foodCategory: "cereales",
    isPerishable: false,
    expiryDate: getExpiryDate(365),
    storageTips: "Conserver dans un endroit sec et à l'abri de la lumière",
    nutritionalInfo: { calories: 130, proteins: 2.7, carbs: 28, fats: 0.3, fiber: 0.4, iron: 1.2 },
    allergens: [],
    isOrganic: true,
    origin: "Inde",
    brand: "Terre Bio",
    unit: "kg",
    // Nouveaux champs
    isVegan: true,
    isVegetarian: true,
    healthScore: 8,
  },
  {
    name: "Pâtes Spaghetti Bio 500g",
    description: "Spaghetti biologiques à base de blé dur, qualité italienne.",
    category: "Épicerie Bio",
    subcategory: "Pâtes",
    price: 2.4,
    comparePrice: 2.8,
    cost: 1.3,
    sku: "PATES-SPAGH-BIO-500G",
    barcode: "1234567891013",
    trackQuantity: true,
    quantity: 150,
    lowStock: 25,
    weight: 0.5,
    dimensions: { length: 25, width: 8, height: 5 },
    images: ["https://images.unsplash.com/photo-1551462147-37885a7d94ac?w=500&auto=format&fit=crop&q=60"],
    status: "active",
    featured: false,
    visibility: "public",
    seoTitle: "Spaghetti Bio 500g - Blé Dur Biologique",
    seoDescription: "Spaghetti biologiques à base de blé dur de qualité italienne",
    productType: "food",
    foodCategory: "cereales",
    isPerishable: false,
    expiryDate: getExpiryDate(365),
    storageTips: "Conserver dans un endroit sec",
    nutritionalInfo: { calories: 131, proteins: 5, carbs: 25, fats: 1.1, fiber: 2.5 },
    allergens: ["gluten"],
    isOrganic: true,
    origin: "Italie",
    brand: "Pasta Bio",
    unit: "paquet",
    // Nouveaux champs
    isVegan: true,
    isVegetarian: true,
    healthScore: 7,
  },

  // ======================
  // BOULANGERIE & CHARCUTERIE
  // ======================
  {
    name: "Pain Campagne Artisanal",
    description: "Pain de campagne artisanal au levain, cuit au feu de bois.",
    category: "Boulangerie",
    subcategory: "Pains",
    price: 3.2,
    comparePrice: 3.6,
    cost: 1.4,
    sku: "PAIN-CAMPAGNE-ART-001",
    barcode: "1234567891014",
    trackQuantity: true,
    quantity: 50,
    lowStock: 8,
    weight: 0.8,
    dimensions: { length: 30, width: 15, height: 10 },
    images: ["https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=60"],
    status: "active",
    featured: true,
    visibility: "public",
    seoTitle: "Pain Campagne Artisanal - Au Levain",
    seoDescription: "Pain de campagne artisanal au levain cuit au feu de bois",
    productType: "food",
    foodCategory: "boulangerie",
    isPerishable: true,
    expiryDate: getExpiryDate(1),
    storageTips: "Conserver dans un torchon à température ambiante",
    nutritionalInfo: { calories: 265, proteins: 9.0, carbs: 53, fats: 1.5, fiber: 2.7, sodium: 480 },
    allergens: ["gluten"],
    isOrganic: false,
    origin: "Boulangerie du Village",
    brand: "Artisans Boulangers",
    unit: "pièce",
    // Nouveaux champs
    isVegan: true,
    isVegetarian: true,
    healthScore: 6,
  },
  {
    name: "Croissants au Beurre",
    description: "Croissants au beurre AOP, croustillants et feuilletés.",
    category: "Boulangerie",
    subcategory: "Viennoiseries",
    price: 1.2,
    comparePrice: 1.4,
    cost: 0.6,
    sku: "CROISSANT-BEURRE-001",
    barcode: "1234567891015",
    trackQuantity: true,
    quantity: 80,
    lowStock: 15,
    weight: 0.1,
    dimensions: { length: 15, width: 8, height: 5 },
    images: ["https://images.unsplash.com/photo-1555507036-ab794f27d2e9?w=500&auto=format&fit=crop&q=60"],
    status: "active",
    featured: false,
    visibility: "public",
    seoTitle: "Croissants au Beurre AOP - Feuilletés",
    seoDescription: "Croissants au beurre AOP croustillants et feuilletés",
    productType: "food",
    foodCategory: "boulangerie",
    isPerishable: true,
    expiryDate: getExpiryDate(1),
    storageTips: "Conserver à température ambiante et consommer le jour même",
    nutritionalInfo: { calories: 406, proteins: 6.6, carbs: 45, fats: 21, fiber: 2.1, cholesterol: 67 },
    allergens: ["gluten", "lactose"],
    isOrganic: false,
    origin: "Boulangerie Parisienne",
    brand: "Maison du Croissant",
    unit: "pièce",
    // Nouveaux champs
    isVegan: false,
    isVegetarian: true,
    healthScore: 4,
  },
  {
    name: "Baguette Tradition",
    description: "Baguette traditionnelle française, croustillante et dorée.",
    category: "Boulangerie",
    subcategory: "Pains",
    price: 1.1,
    comparePrice: 1.3,
    cost: 0.4,
    sku: "BAGUETTE-TRAD-001",
    barcode: "1234567891016",
    trackQuantity: true,
    quantity: 60,
    lowStock: 10,
    weight: 0.25,
    dimensions: { length: 60, width: 5, height: 5 },
    images: ["https://images.unsplash.com/photo-1572552635104-d0d16b040b24?w=500&auto=format&fit=crop&q=60"],
    status: "active",
    featured: false,
    visibility: "public",
    seoTitle: "Baguette Tradition - Boulangerie Artisanale",
    seoDescription: "Baguette traditionnelle française croustillante et dorée",
    productType: "food",
    foodCategory: "boulangerie",
    isPerishable: true,
    expiryDate: getExpiryDate(1),
    storageTips: "Consommer dans la journée",
    nutritionalInfo: { calories: 290, proteins: 10, carbs: 58, fats: 1.5, fiber: 2.5 },
    allergens: ["gluten"],
    isOrganic: false,
    origin: "Boulangerie du Quartier",
    brand: "Artisans Boulangers",
    unit: "pièce",
    // Nouveaux champs
    isVegan: true,
    isVegetarian: true,
    healthScore: 6,
  },
  {
    name: "Pain au Chocolat",
    description: "Pain au chocolat artisanal, pâte feuilletée et chocolat noir.",
    category: "Boulangerie",
    subcategory: "Viennoiseries",
    price: 1.4,
    comparePrice: 1.6,
    cost: 0.7,
    sku: "PAIN-CHOCOLAT-001",
    barcode: "1234567891017",
    trackQuantity: true,
    quantity: 70,
    lowStock: 12,
    weight: 0.1,
    dimensions: { length: 12, width: 8, height: 5 },
    images: ["https://images.unsplash.com/photo-1558310442-0d8f9f36c539?w=500&auto=format&fit=crop&q=60"],
    status: "active",
    featured: false,
    visibility: "public",
    seoTitle: "Pain au Chocolat Artisanal - Chocolat Noir",
    seoDescription: "Pain au chocolat artisanal avec chocolat noir de qualité",
    productType: "food",
    foodCategory: "boulangerie",
    isPerishable: true,
    expiryDate: getExpiryDate(1),
    storageTips: "Consommer le jour même pour plus de croustillant",
    nutritionalInfo: { calories: 385, proteins: 6.1, carbs: 42, fats: 21, fiber: 2.3 },
    allergens: ["gluten", "lactose"],
    isOrganic: false,
    origin: "Boulangerie Parisienne",
    brand: "Maison du Croissant",
    unit: "pièce",
    // Nouveaux champs
    isVegan: false,
    isVegetarian: true,
    healthScore: 4,
  },
  {
    name: "Jambon de Bayonne",
    description: "Jambon de Bayonne affiné 12 mois, saveur authentique.",
    category: "Charcuterie",
    subcategory: "Jambons",
    price: 24.9,
    comparePrice: 28.5,
    cost: 16.0,
    sku: "JAMBON-BAYONNE-001",
    barcode: "1234567891018",
    trackQuantity: true,
    quantity: 25,
    lowStock: 5,
    weight: 0.2,
    dimensions: { length: 25, width: 12, height: 5 },
    images: ["https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=500&auto=format&fit=crop&q=60"],
    status: "active",
    featured: true,
    visibility: "public",
    seoTitle: "Jambon de Bayonne Affiné 12 mois",
    seoDescription: "Jambon de Bayonne traditionnel affiné 12 mois",
    productType: "food",
    foodCategory: "charcuterie",
    isPerishable: true,
    expiryDate: getExpiryDate(30),
    storageTips: "Conserver au réfrigérateur après ouverture",
    nutritionalInfo: { calories: 250, proteins: 30, carbs: 1, fats: 13, sodium: 1500 },
    allergens: [],
    isOrganic: false,
    origin: "Pays Basque, France",
    brand: "Salaisons du Sud-Ouest",
    unit: "kg",
    // Nouveaux champs
    isVegan: false,
    isVegetarian: false,
    healthScore: 5,
  },
  {
    name: "Saucisson Sec Artisanal",
    description: "Saucisson sec artisanal affiné 6 mois, aux herbes de Provence.",
    category: "Charcuterie",
    subcategory: "Saucissons",
    price: 18.5,
    comparePrice: 21.0,
    cost: 11.2,
    sku: "SAUCISSON-SEC-ART",
    barcode: "1234567891019",
    trackQuantity: true,
    quantity: 35,
    lowStock: 7,
    weight: 0.4,
    dimensions: { length: 20, width: 8, height: 8 },
    images: ["https://images.unsplash.com/photo-1606811841685-b30c263852bb?w=500&auto=format&fit=crop&q=60"],
    status: "active",
    featured: false,
    visibility: "public",
    seoTitle: "Saucisson Sec Artisanal - Herbes de Provence",
    seoDescription: "Saucisson sec artisanal affiné 6 mois aux herbes de Provence",
    productType: "food",
    foodCategory: "charcuterie",
    isPerishable: true,
    expiryDate: getExpiryDate(60),
    storageTips: "Conserver à température ambiante avant ouverture",
    nutritionalInfo: { calories: 380, proteins: 25, carbs: 2, fats: 31, sodium: 1800 },
    allergens: [],
    isOrganic: false,
    origin: "Ardèche, France",
    brand: "Salaisons Ardéchoises",
    unit: "pièce",
    // Nouveaux champs
    isVegan: false,
    isVegetarian: false,
    healthScore: 4,
  },
  {
    name: "Fromage de Chèvre Frais",
    description: "Fromage de chèvre frais crémeux, idéal pour l'apéritif.",
    category: "Fromagerie",
    subcategory: "Fromages de Chèvre",
    price: 4.2,
    comparePrice: 4.8,
    cost: 2.5,
    sku: "FROM-CHEVRE-FRAIS-001",
    barcode: "1234567891020",
    trackQuantity: true,
    quantity: 45,
    lowStock: 8,
    weight: 0.2,
    dimensions: { length: 10, width: 10, height: 5 },
    images: ["https://images.unsplash.com/photo-1486297678162-eb2a1b331e84?w=500&auto=format&fit=crop&q=60"],
    status: "active",
    featured: false,
    visibility: "public",
    seoTitle: "Fromage de Chèvre Frais - Produit Artisanal",
    seoDescription: "Fromage de chèvre frais crémeux de qualité artisanale",
    productType: "food",
    foodCategory: "fromages",
    isPerishable: true,
    expiryDate: getExpiryDate(10),
    storageTips: "Conserver au réfrigérateur dans son emballage",
    nutritionalInfo: { calories: 104, proteins: 7.0, carbs: 1.0, fats: 8.0, calcium: 90, sodium: 180 },
    allergens: ["lactose"],
    isOrganic: false,
    origin: "Périgord, France",
    brand: "Fromagerie du Périgord",
    unit: "pièce",
    // Nouveaux champs
    isVegan: false,
    isVegetarian: true,
    healthScore: 5,
  },
  {
    name: "Comté AOP 18 mois",
    description: "Comté AOP affiné 18 mois, saveur fruitée et noisettée.",
    category: "Fromagerie",
    subcategory: "Fromages à Pâte Pressée",
    price: 28.9,
    comparePrice: 32.5,
    cost: 18.5,
    sku: "COMTE-AOP-18MOIS",
    barcode: "1234567891021",
    trackQuantity: true,
    quantity: 20,
    lowStock: 4,
    weight: 0.3,
    dimensions: { length: 15, width: 12, height: 8 },
    images: ["https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=500&auto=format&fit=crop&q=60"],
    status: "active",
    featured: true,
    visibility: "public",
    seoTitle: "Comté AOP 18 mois - Fromage Affiné",
    seoDescription: "Comté AOP affiné 18 mois aux saveurs fruitées et noisettées",
    productType: "food",
    foodCategory: "fromages",
    isPerishable: true,
    expiryDate: getExpiryDate(21),
    storageTips: "Conserver au frais dans un torchon humide",
    nutritionalInfo: { calories: 415, proteins: 27, carbs: 1, fats: 34, calcium: 1100, sodium: 650 },
    allergens: ["lactose"],
    isOrganic: false,
    origin: "Jura, France",
    brand: "Fromageries du Jura",
    unit: "kg",
    // Nouveaux champs
    isVegan: false,
    isVegetarian: true,
    healthScore: 5,
  },
  {
    name: "Brie de Meaux AOP",
    description: "Brie de Meaux AOP, fromage crémeux à pâte molle.",
    category: "Fromagerie",
    subcategory: "Fromages à Pâte Molle",
    price: 12.5,
    comparePrice: 14.2,
    cost: 7.8,
    sku: "BRIE-MEAUX-AOP",
    barcode: "1234567891022",
    trackQuantity: true,
    quantity: 30,
    lowStock: 6,
    weight: 0.25,
    dimensions: { length: 20, width: 20, height: 3 },
    images: ["https://images.unsplash.com/photo-1563245372-f21724e2256c?w=500&auto=format&fit=crop&q=60"],
    status: "active",
    featured: false,
    visibility: "public",
    seoTitle: "Brie de Meaux AOP - Fromage Crémeux",
    seoDescription: "Brie de Meaux AOP, fromage crémeux à pâte molle au lait cru",
    productType: "food",
    foodCategory: "fromages",
    isPerishable: true,
    expiryDate: getExpiryDate(14),
    storageTips: "Sortir du réfrigérateur 1h avant dégustation",
    nutritionalInfo: { calories: 334, proteins: 21, carbs: 0.5, fats: 28, calcium: 184, sodium: 629 },
    allergens: ["lactose"],
    isOrganic: false,
    origin: "Île-de-France, France",
    brand: "Fromageries de Brie",
    unit: "pièce",
    // Nouveaux champs
    isVegan: false,
    isVegetarian: true,
    healthScore: 5,
  },

  // ======================
  // CAVE & VINS
  // ======================
  {
    name: "Bordeaux Rouge 2019",
    description: "Vin rouge de Bordeaux, assemblage traditionnel, belle structure.",
    category: "Vins",
    subcategory: "Vins Rouges",
    price: 18.9,
    comparePrice: 22.5,
    cost: 12.0,
    sku: "BORDEAUX-ROUGE-2019",
    barcode: "1234567891023",
    trackQuantity: true,
    quantity: 60,
    lowStock: 10,
    weight: 1.3,
    dimensions: { length: 8, width: 8, height: 30 },
    images: ["https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=500&auto=format&fit=crop&q=60"],
    status: "active",
    featured: true,
    visibility: "public",
    seoTitle: "Bordeaux Rouge 2019 - Appellation Contrôlée",
    seoDescription: "Vin rouge de Bordeaux traditionnel millésime 2019",
    productType: "food",
    foodCategory: "vins-rouges",
    isPerishable: false,
    expiryDate: getExpiryDate(1825),
    storageTips: "Conserver à l'abri de la lumière, température constante 12-14°C",
    nutritionalInfo: { calories: 85, carbs: 2.6, sugar: 0.8 },
    allergens: ["sulfites"],
    isOrganic: false,
    origin: "Bordeaux, France",
    brand: "Château Tradition",
    unit: "bouteille",
    // Nouveaux champs
    isVegan: true,
    isVegetarian: true,
    healthScore: 3,
  },
  {
    name: "Sancerre Blanc 2022",
    description: "Vin blanc de Sancerre, frais et minéral, aux arômes d'agrumes.",
    category: "Vins",
    subcategory: "Vins Blancs",
    price: 22.5,
    comparePrice: 26.0,
    cost: 15.0,
    sku: "SANCERRE-BLANC-2022",
    barcode: "1234567891024",
    trackQuantity: true,
    quantity: 45,
    lowStock: 8,
    weight: 1.3,
    dimensions: { length: 8, width: 8, height: 30 },
    images: ["https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=500&auto=format&fit=crop&q=60"],
    status: "active",
    featured: false,
    visibility: "public",
    seoTitle: "Sancerre Blanc 2022 - Sauvignon Blanc",
    seoDescription: "Vin blanc de Sancerre frais et aromatique millésime 2022",
    productType: "food",
    foodCategory: "vins-blancs",
    isPerishable: false,
    expiryDate: getExpiryDate(1095),
    storageTips: "Servir frais à 8-10°C",
    nutritionalInfo: { calories: 82, carbs: 2.3, sugar: 0.6 },
    allergens: ["sulfites"],
    isOrganic: true,
    origin: "Loire, France",
    brand: "Domaine des Olivettes",
    unit: "bouteille",
    // Nouveaux champs
    isVegan: true,
    isVegetarian: true,
    healthScore: 3,
  },
  {
    name: "Champagne Brut Réserve",
    description: "Champagne brut traditionnel, fine bulle et notes de brioche.",
    category: "Champagnes",
    subcategory: "Brut",
    price: 42.9,
    comparePrice: 49.9,
    cost: 28.0,
    sku: "CHAMP-BRUT-RESERVE",
    barcode: "1234567891025",
    trackQuantity: true,
    quantity: 30,
    lowStock: 5,
    weight: 1.3,
    dimensions: { length: 8, width: 8, height: 30 },
    images: ["https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=500&auto=format&fit=crop&q=60"],
    status: "active",
    featured: true,
    visibility: "public",
    seoTitle: "Champagne Brut Réserve - Tradition Française",
    seoDescription: "Champagne brut traditionnel aux notes de brioche et fruits secs",
    productType: "food",
    foodCategory: "champagnes",
    isPerishable: false,
    expiryDate: getExpiryDate(1825),
    storageTips: "Servir frais à 6-8°C",
    nutritionalInfo: { calories: 80, carbs: 1.5, sugar: 0.5 },
    allergens: ["sulfites"],
    isOrganic: false,
    origin: "Champagne, France",
    brand: "Maison Champenoise",
    unit: "bouteille",
    // Nouveaux champs
    isVegan: true,
    isVegetarian: true,
    healthScore: 3,
  },
  {
    name: "Rosé de Provence 2023",
    description: "Vin rosé de Provence, frais et fruité, idéal pour l'été.",
    category: "Vins",
    subcategory: "Vins Rosés",
    price: 12.9,
    comparePrice: 14.8,
    cost: 8.5,
    sku: "ROSE-PROVENCE-2023",
    barcode: "1234567891026",
    trackQuantity: true,
    quantity: 75,
    lowStock: 12,
    weight: 1.3,
    dimensions: { length: 8, width: 8, height: 30 },
    images: ["https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=500&auto=format&fit=crop&q=60"],
    status: "active",
    featured: false,
    visibility: "public",
    seoTitle: "Rosé de Provence 2023 - Frais et Fruité",
    seoDescription: "Vin rosé de Provence frais et fruité millésime 2023",
    productType: "food",
    foodCategory: "vins-roses",
    isPerishable: false,
    expiryDate: getExpiryDate(730),
    storageTips: "Servir frais à 8-10°C",
    nutritionalInfo: { calories: 83, carbs: 2.1, sugar: 0.4 },
    allergens: ["sulfites"],
    isOrganic: false,
    origin: "Provence, France",
    brand: "Domaine Provençal",
    unit: "bouteille",
    // Nouveaux champs
    isVegan: true,
    isVegetarian: true,
    healthScore: 3,
  },
  {
    name: "Bourgogne Pinot Noir 2020",
    description: "Bourgogne rouge élégant au Pinot Noir, arômes de fruits rouges.",
    category: "Vins",
    subcategory: "Vins Rouges",
    price: 25.9,
    comparePrice: 29.5,
    cost: 16.8,
    sku: "BOURGOGNE-PN-2020",
    barcode: "1234567891027",
    trackQuantity: true,
    quantity: 40,
    lowStock: 8,
    weight: 1.3,
    dimensions: { length: 8, width: 8, height: 30 },
    images: ["https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=500&auto=format&fit=crop&q=60"],
    status: "active",
    featured: true,
    visibility: "public",
    seoTitle: "Bourgogne Pinot Noir 2020 - Élégant et Fruité",
    seoDescription: "Bourgogne rouge élégant au Pinot Noir millésime 2020",
    productType: "food",
    foodCategory: "vins-rouges",
    isPerishable: false,
    expiryDate: getExpiryDate(1460),
    storageTips: "Servir à 14-16°C",
    nutritionalInfo: { calories: 87, carbs: 2.8, sugar: 0.9 },
    allergens: ["sulfites"],
    isOrganic: true,
    origin: "Bourgogne, France",
    brand: "Domaine Bourguignon",
    unit: "bouteille",
    // Nouveaux champs
    isVegan: true,
    isVegetarian: true,
    healthScore: 3,
  },
  {
    name: "Whisky Single Malt 12 ans",
    description: "Whisky single malt écossais vieilli 12 ans en fûts de chêne.",
    category: "Spiritueux",
    subcategory: "Whiskies",
    price: 45.9,
    comparePrice: 52.0,
    cost: 28.5,
    sku: "WHISKY-SM-12ANS",
    barcode: "1234567891028",
    trackQuantity: true,
    quantity: 25,
    lowStock: 5,
    weight: 1.4,
    dimensions: { length: 10, width: 10, height: 25 },
    images: ["https://images.unsplash.com/photo-1608270586620-248524c67de9?w=500&auto=format&fit=crop&q=60"],
    status: "active",
    featured: false,
    visibility: "public",
    seoTitle: "Whisky Single Malt 12 ans - Vieilli en Fût de Chêne",
    seoDescription: "Whisky single malt écossais vieilli 12 ans en fûts de chêne",
    productType: "food",
    foodCategory: "spiritueux",
    isPerishable: false,
    expiryDate: getExpiryDate(3650),
    storageTips: "Conserver à l'abri de la lumière, servir à température ambiante",
    nutritionalInfo: { calories: 250, carbs: 0.1, sugar: 0.1, alcohol: 40 },
    allergens: [],
    isOrganic: false,
    origin: "Écosse",
    brand: "Highland Distillery",
    unit: "bouteille",
    // Nouveaux champs
    isVegan: true,
    isVegetarian: true,
    healthScore: 2,
  },

  // ======================
  // RESTAURANT
  // ======================
  {
    name: "Salade César au Poulet",
    description: "Salade César traditionnelle avec poulet grillé et parmesan.",
    category: "Plats Préparés",
    subcategory: "Salades",
    price: 8.9,
    comparePrice: 10.5,
    cost: 4.5,
    sku: "SALADE-CESAR-POULET",
    barcode: "1234567891029",
    trackQuantity: true,
    quantity: 20,
    lowStock: 5,
    weight: 0.4,
    dimensions: { length: 15, width: 15, height: 8 },
    images: ["https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=500&auto=format&fit=crop&q=60"],
    status: "active",
    featured: true,
    visibility: "public",
    seoTitle: "Salade César au Poulet - Préparée Fraîche",
    seoDescription: "Salade César traditionnelle avec poulet grillé et parmesan",
    productType: "food",
    foodCategory: "plats-prepares",
    isPerishable: true,
    expiryDate: getExpiryDate(1),
    storageTips: "Conserver au réfrigérateur et consommer dans les 24h",
    nutritionalInfo: { calories: 320, proteins: 25, carbs: 12, fats: 18, fiber: 3 },
    allergens: ["lactose", "gluten"],
    isOrganic: false,
    origin: "Préparé sur place",
    brand: "Notre Restaurant",
    unit: "portion",
    // Nouveaux champs
    isVegan: false,
    isVegetarian: false,
    healthScore: 5,
  },
  {
    name: "Tarte aux Pommes Maison",
    description: "Tarte aux pommes traditionnelle avec une pâte sablée maison.",
    category: "Pâtisseries",
    subcategory: "Tartes",
    price: 5.9,
    comparePrice: 6.9,
    cost: 2.8,
    sku: "TARTE-POMMES-MSN",
    barcode: "1234567891031",
    trackQuantity: true,
    quantity: 12,
    lowStock: 2,
    weight: 0.8,
    dimensions: { length: 25, width: 25, height: 5 },
    images: ["https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500&auto=format&fit=crop&q=60"],
    status: "active",
    featured: true,
    visibility: "public",
    seoTitle: "Tarte aux Pommes Maison - Pâtisserie Fraîche",
    seoDescription: "Tarte aux pommes traditionnelle avec pâte sablée maison",
    productType: "food",
    foodCategory: "patisseries",
    isPerishable: true,
    expiryDate: getExpiryDate(2),
    storageTips: "Conserver à température ambiante",
    nutritionalInfo: { calories: 280, proteins: 3, carbs: 45, fats: 10, fiber: 2, sugar: 25 },
    allergens: ["gluten", "lactose"],
    isOrganic: false,
    origin: "Préparé sur place",
    brand: "Notre Restaurant",
    unit: "part",
    // Nouveaux champs
    isVegan: false,
    isVegetarian: true,
    healthScore: 4,
  },
  {
    name: "Croque-Monsieur",
    description: "Croque-monsieur traditionnel au jambon et fromage fondant.",
    category: "Plats Préparés",
    subcategory: "Sandwichs",
    price: 4.9,
    comparePrice: 5.5,
    cost: 2.4,
    sku: "CROQUE-MONSIEUR",
    barcode: "1234567891032",
    trackQuantity: true,
    quantity: 18,
    lowStock: 4,
    weight: 0.3,
    dimensions: { length: 18, width: 12, height: 4 },
    images: ["https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=500&auto=format&fit=crop&q=60"],
    status: "active",
    featured: false,
    visibility: "public",
    seoTitle: "Croque-Monsieur Traditionnel - Jambon Fromage",
    seoDescription: "Croque-monsieur traditionnel au jambon et fromage fondant",
    productType: "food",
    foodCategory: "plats-prepares",
    isPerishable: true,
    expiryDate: getExpiryDate(1),
    storageTips: "Réchauffer 5 min au four avant dégustation",
    nutritionalInfo: { calories: 420, proteins: 18, carbs: 35, fats: 22, fiber: 2 },
    allergens: ["gluten", "lactose"],
    isOrganic: false,
    origin: "Préparé sur place",
    brand: "Notre Restaurant",
    unit: "pièce",
    // Nouveaux champs
    isVegan: false,
    isVegetarian: false,
    healthScore: 4,
  },
  {
    name: "Soupe à l'Oignon Gratinée",
    description: "Soupe à l'oignon traditionnelle gratinée au fromage.",
    category: "Plats Préparés",
    subcategory: "Soupes",
    price: 5.5,
    comparePrice: 6.2,
    cost: 2.7,
    sku: "SOUPE-OIGNON-GRAT",
    barcode: "1234567891033",
    trackQuantity: true,
    quantity: 15,
    lowStock: 3,
    weight: 0.5,
    dimensions: { length: 12, width: 12, height: 10 },
    images: ["https://images.unsplash.com/photo-1547592166-23ac45744acd?w=500&auto=format&fit=crop&q=60"],
    status: "active",
    featured: false,
    visibility: "public",
    seoTitle: "Soupe à l'Oignon Gratinée - Recette Traditionnelle",
    seoDescription: "Soupe à l'oignon traditionnelle gratinée au fromage",
    productType: "food",
    foodCategory: "plats-prepares",
    isPerishable: true,
    expiryDate: getExpiryDate(2),
    storageTips: "Réchauffer 10 min au four à 180°C",
    nutritionalInfo: { calories: 280, proteins: 12, carbs: 25, fats: 14, fiber: 3 },
    allergens: ["lactose", "gluten"],
    isOrganic: false,
    origin: "Préparé sur place",
    brand: "Notre Restaurant",
    unit: "portion",
    // Nouveaux champs
    isVegan: false,
    isVegetarian: true,
    healthScore: 5,
  },
  {
    name: "Éclair au Chocolat",
    description: "Éclair au chocolat, pâte à choux et crème pâtissière au chocolat.",
    category: "Pâtisseries",
    subcategory: "Éclairs",
    price: 3.8,
    comparePrice: 4.2,
    cost: 1.9,
    sku: "ECLAIR-CHOCOLAT",
    barcode: "1234567891034",
    trackQuantity: true,
    quantity: 25,
    lowStock: 5,
    weight: 0.15,
    dimensions: { length: 12, width: 5, height: 5 },
    images: ["https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500&auto=format&fit=crop&q=60"],
    status: "active",
    featured: false,
    visibility: "public",
    seoTitle: "Éclair au Chocolat - Pâtisserie Fraîche",
    seoDescription: "Éclair au chocolat avec crème pâtissière maison",
    productType: "food",
    foodCategory: "patisseries",
    isPerishable: true,
    expiryDate: getExpiryDate(2),
    storageTips: "Conserver au réfrigérateur",
    nutritionalInfo: { calories: 245, proteins: 4, carbs: 32, fats: 12, fiber: 1, sugar: 20 },
    allergens: ["gluten", "lactose", "oeuf"],
    isOrganic: false,
    origin: "Préparé sur place",
    brand: "Notre Restaurant",
    unit: "pièce",
    // Nouveaux champs
    isVegan: false,
    isVegetarian: true,
    healthScore: 3,
  }
];

// Fonction pour générer un slug à partir du nom
function generateSlug(name) {
  return name
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)+/g, "")
    .substring(0, 100);
}

async function main() {
  console.log("🌱 Début du seeding des produits alimentaires avec foodCategory...");

  try {
    // Récupérer tous les utilisateurs existants
    const users = await prisma.user.findMany({
      select: { id: true },
    });

    if (users.length === 0) {
      console.log("❌ Aucun utilisateur trouvé dans la base de données");
      console.log("💡 Veuillez d'abord créer des utilisateurs avant de lancer ce seed");
      return;
    }

    console.log(`👥 ${users.length} utilisateurs trouvés`);

    // Vérifier s'il y a déjà des produits alimentaires
    const existingFoodProducts = await prisma.product.count({
      where: {
        productType: "food",
      },
    });

    if (existingFoodProducts > 0) {
      console.log(`⚠️  ${existingFoodProducts} produits alimentaires existants détectés`);
      console.log("🗑️  Suppression des anciens produits alimentaires...");
      await prisma.product.deleteMany({
        where: {
          productType: "food",
        },
      });
      console.log("✅ Anciens produits alimentaires supprimés");
    }

    // Créer les produits alimentaires
    console.log(`🛍️  Création de ${foodProductsData.length} produits alimentaires...`);

    for (const productData of foodProductsData) {
      // Sélectionner un utilisateur au hasard
      const randomUser = users[Math.floor(Math.random() * users.length)];

      // Générer le slug
      const slug = generateSlug(productData.name);

      await prisma.product.create({
        data: {
          ...productData,
          slug,
          userId: randomUser.id,
          publishedAt: productData.status === "active" ? new Date() : null,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      });

      console.log(`✅ Produit alimentaire créé: ${productData.name}`);
    }

    console.log("🎉 Seeding des produits alimentaires terminé avec succès!");
    console.log(`📊 ${foodProductsData.length} produits alimentaires créés`);

    // Afficher un résumé par foodCategory
    const productsByFoodCategory = await prisma.product.groupBy({
      by: ["foodCategory"],
      where: {
        productType: "food",
      },
      _count: {
        id: true,
      },
    });

    console.log("\n📈 Résumé par foodCategory:");
    productsByFoodCategory.forEach((cat) => {
      console.log(`   ${cat.foodCategory}: ${cat._count.id} produits`);
    });

    // Résumé par catégorie traditionnelle
    const productsByCategory = await prisma.product.groupBy({
      by: ["category"],
      where: {
        productType: "food",
      },
      _count: {
        id: true,
      },
    });

    console.log("\n🥦 Résumé par catégorie:");
    productsByCategory.forEach((cat) => {
      console.log(`   ${cat.category}: ${cat._count.id} produits`);
    });

    // Résumé par type de régime
    const veganCount = await prisma.product.count({
      where: {
        productType: "food",
        isVegan: true,
      },
    });

    const vegetarianCount = await prisma.product.count({
      where: {
        productType: "food",
        isVegetarian: true,
      },
    });

    console.log("\n🌱 Résumé par type de régime:");
    console.log(`   Produits Vegan: ${veganCount}`);
    console.log(`   Produits Végétariens: ${vegetarianCount}`);
    console.log(`   Produits Non-végétariens: ${foodProductsData.length - vegetarianCount}`);

    // Résumé par score santé
    const healthScoreStats = await prisma.product.groupBy({
      by: ["healthScore"],
      where: {
        productType: "food",
      },
      _count: {
        id: true,
      },
      orderBy: {
        healthScore: "asc",
      },
    });

    console.log("\n💚 Résumé par score santé:");
    healthScoreStats.forEach((stat) => {
      console.log(`   Score ${stat.healthScore}: ${stat._count.id} produits`);
    });

  } catch (error) {
    console.error("❌ Erreur lors du seeding des produits alimentaires:", error);
    throw error;
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });