import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

async function main() {
  try {
    console.log("🌱 Seeding database with provided data...");
    // Suppression des données existantes

    await prisma.category.deleteMany();
    await prisma.metierService.deleteMany();
    await prisma.service.deleteMany();
    await prisma.metier.deleteMany();
    console.log("✓ Catégories existantes supprimées");

    // Création des nouvelles catégories
    const categories = await prisma.category.createMany({
      data: [
        { name: "Prestations intérieures" },
        { name: "Prestations extérieures" },
        { name: "Constructions" },
      ],
    });
    // =======================
    // MÉTIERS
    // =======================
    const metiersData = [
      { id: 1, libelle: "ABF (Architecte Bâtiment de France)" },
      { id: 2, libelle: "Agence D'urbanisme" },
      { id: 3, libelle: "Agenceur (euse) - Désigner d'intérieur" },
      { id: 4, libelle: "Agent de nettoyage - Propreté" },
      { id: 5, libelle: "Agence Incendie - Sécurité" },
      { id: 6, libelle: "Agent Immobilier - Administrateur de biens " },
      { id: 7, libelle: "Aménageur - Lotisseur" },
      { id: 8, libelle: "Aménageur Extérieur" },
      { id: 9, libelle: "Aménageur Intérieur" },
      { id: 10, libelle: "Architecte " },
      { id: 11, libelle: "Architected Intérieur" },
      { id: 12, libelle: "Arroseur " },
      { id: 13, libelle: "Ascensoriste" },
      { id: 14, libelle: "Assureur" },
      { id: 15, libelle: "Auditeur" },
      { id: 16, libelle: "Avocat" },
      { id: 17, libelle: "Bailleur Social" },
      { id: 18, libelle: "Banquier" },
      { id: 19, libelle: "Bardeur" },
      { id: 20, libelle: "Bricoleur" },
      { id: 21, libelle: "Bureau d'étude" },
      { id: 22, libelle: "Cableur" },
      { id: 23, libelle: "Calculateur et raitement des vibrations et chocs" },
      { id: 24, libelle: "Canalisateur" },
      { id: 25, libelle: "Carreleur" },
      { id: 26, libelle: "Certifcateur - Contrôleur" },
      { id: 27, libelle: "Charpentier bois" },
      { id: 28, libelle: "Charpentier Métallique" },
      { id: 29, libelle: "Chef de Chantier" },
      { id: 30, libelle: "Cimentier" },
      { id: 31, libelle: "Clerc de Notaire" },
      { id: 32, libelle: "Coffreur" },
      { id: 33, libelle: "Compresseur" },
      { id: 34, libelle: "Concasseur" },
      { id: 35, libelle: "Concepteur" },
      { id: 36, libelle: "Conducteur de travaux" },
      { id: 37, libelle: "Consciergerie" },
      { id: 38, libelle: "Conseiller Assurance" },
      { id: 39, libelle: "Conseiller bancaire" },
      { id: 40, libelle: "Conseiller en gestion de patrimoine" },
      { id: 41, libelle: "Conseiller Immobilier" },
      { id: 42, libelle: "Conseiller télécom" },
      { id: 43, libelle: "Constructeur" },
      { id: 44, libelle: "Constructeur de maison en Contenaire" },
      { id: 45, libelle: "Contrôleur Bâtiment" },
      { id: 46, libelle: "Contrôleur d'accés" },
      { id: 47, libelle: "Contructeurs de maison en bois" },
      { id: 48, libelle: "Courtier" },
      { id: 49, libelle: "Couvreur" },
      { id: 50, libelle: "Couvreur" },
      { id: 51, libelle: "Cuisiniste" },
      { id: 52, libelle: "Dalleur" },
      { id: 53, libelle: "Dalleur" },
      { id: 54, libelle: "Décorateur intérieur" },
      { id: 55, libelle: "Découpeur" },
      { id: 56, libelle: "Déménageur" },
      { id: 57, libelle: "Démolisseur" },
      { id: 58, libelle: "Dératiseur - Désinfecteur" },
      { id: 59, libelle: "Désamianteur" },
      { id: 60, libelle: "Désenfumeur" },
      { id: 61, libelle: "Déssinateur" },
      { id: 62, libelle: "Déssinateur en bâtiment" },
      { id: 63, libelle: "Diagnostiqueur" },
      { id: 64, libelle: "Domoticien" },
      { id: 65, libelle: "Ébéniste" },
      { id: 66, libelle: "Ebéniste" },
      { id: 67, libelle: "Échafaudeur" },
      { id: 68, libelle: "Echaffaudeur" },
      { id: 69, libelle: "Eclairagiste" },
      { id: 70, libelle: "Electricien" },
      { id: 71, libelle: "Enduiseur" },
      { id: 72, libelle: "Etancheur" },
      { id: 73, libelle: "Étancheur - Étanchéiste" },
      { id: 74, libelle: "Expert en assurance" },
      { id: 75, libelle: "Expert Immobilier" },
      { id: 76, libelle: "Facadier" },
      { id: 77, libelle: "Fleuriste" },
      { id: 78, libelle: "Fontainier" },
      { id: 79, libelle: "Forreur" },
      { id: 80, libelle: "Frigoriste" },
      { id: 81, libelle: "Géomètre" },
      { id: 82, libelle: "Gestionnaire de copropriété - Syndic" },
      { id: 83, libelle: "Gestionnaire de Sinistre" },
      { id: 84, libelle: "Ingénieur" },
      { id: 85, libelle: "Ingénieur Civil" },
      { id: 86, libelle: "Ingénieur en Batiment" },
      { id: 87, libelle: "Ingénieur en Patrimoine - Conseiller Patrimonial" },
      { id: 88, libelle: "Ingénieur environnement" },
      { id: 89, libelle: "Ingénieur Infrastructure" },
      { id: 90, libelle: "Installateur - Installatrice en Sanitaires" },
      { id: 91, libelle: "Installateur(trice) d'alarme" },
      { id: 92, libelle: "Isolateur" },
      { id: 93, libelle: "Jardinier" },
      { id: 94, libelle: "Juriste" },
      { id: 95, libelle: "Maçon" },
      { id: 96, libelle: "Entreprise deViabilistation, VRD, Terrassement" },
      { id: 97, libelle: "Marbriers" },
      { id: 98, libelle: "Menuisier Aluminium et Alliage" },
      { id: 99, libelle: "Menuisier Bois et Charpente" },
      { id: 100, libelle: "Menuisier Metallique" },
      { id: 101, libelle: "Menuisier métalliques" },
      { id: 102, libelle: "Menuisier Portes et Fenêtres" },
      { id: 103, libelle: "Menuisier PVC" },
      { id: 104, libelle: "Metreur" },
      { id: 105, libelle: "Miroitier" },
      { id: 106, libelle: "Monnteur en Installation de panneau Solaire" },
      { id: 107, libelle: "Monteur de Chaudiere " },
      { id: 108, libelle: "Monteur en Installation d'isolant" },
      { id: 109, libelle: "Monteur en Installation de Climatisation" },
      { id: 110, libelle: "Monteur en Installation de fosse septique" },
      { id: 111, libelle: "Monteur en Installation de panneau photovoltaique" },
      { id: 112, libelle: "Monteur en installation de Store - Volet Roullant" },
      { id: 113, libelle: "Monteur en installation Sanitaire" },
      { id: 114, libelle: "Monteur en Installation Thermiques" },
      { id: 115, libelle: "Monteur en Installations de Barrière de Sécurité " },
      { id: 116, libelle: "Monteur en Installations de Pergola" },
      {
        id: 117,
        libelle: "Monteur en Installations de volet Persiennes et jalousies",
      },
      { id: 118, libelle: "Monteur et Installateur de Caillebotis" },
      { id: 119, libelle: "Monteur et Installateur de Cheminés" },
      { id: 120, libelle: "Monteur et Installateur de Cloture" },
      { id: 121, libelle: "Monteur et Installateur de Gazon" },
      { id: 122, libelle: "Monteur et Installateur de Gouttiere" },
      {
        id: 123,
        libelle: "Monteur et Installateur de Grilles et Rideaux métalliques",
      },
      { id: 124, libelle: "Monteur et Installateur de Jaccuzi" },
      { id: 125, libelle: "Monteur et Installateur de Moustiquaire" },
      { id: 126, libelle: "Monteur et Installateur de Panneau d'affichage" },
      { id: 127, libelle: "Monteur et Installateur de Parquet" },
      {
        id: 128,
        libelle: "Monteur et Installateur de Pergolas Biocliamtiques",
      },
      { id: 129, libelle: "Monteur et Installateur de Placards" },
      { id: 130, libelle: "Monteur et Installateur de SPA" },
      { id: 131, libelle: "Monteur et Installateur de Tôle - Tôlerie " },
      { id: 132, libelle: "Monteur et Installateur en Domotique" },
      { id: 133, libelle: "Moquettiste" },
      { id: 134, libelle: "Muraillier " },
      { id: 135, libelle: "Muralier" },
      { id: 136, libelle: "Nettoyeur" },
      { id: 137, libelle: "Notaire" },
      { id: 138, libelle: "Onduleur" },
      { id: 139, libelle: "Outilleur" },
      { id: 140, libelle: "Parquetteur" },
      { id: 141, libelle: "Paysagiste " },
      { id: 142, libelle: "Peintre" },
      { id: 143, libelle: "Pisciniste" },
      { id: 144, libelle: "Plaquiste" },
      { id: 145, libelle: "Platrier - Plaquiste" },
      { id: 146, libelle: "Plombier" },
      { id: 147, libelle: "Polisseur " },
      { id: 148, libelle: "Poseur de Comopteur d'eau" },
      { id: 149, libelle: "Poseur de Compteur Gaz" },
      { id: 150, libelle: "Promoteur" },
      { id: 151, libelle: "Quincaillier" },
      { id: 152, libelle: "Ramoneur" },
      { id: 153, libelle: "Ravaleur" },
      { id: 154, libelle: "Récupérateur d'eau" },
      { id: 155, libelle: "Récupérateur et traiteur d'aluminium" },
      { id: 156, libelle: "Récupérateur et traiteur de boois" },
      { id: 157, libelle: "Récupérateur et traiteur de déchets" },
      { id: 158, libelle: "Récupérateur et traiteur de fer" },
      { id: 159, libelle: "Récupérateur et traiteur plastiques" },
      { id: 160, libelle: "Régleur de chaudiere, chauffage" },
      { id: 161, libelle: "Réhabilitateur" },
      { id: 162, libelle: "Réparateur d'appareil éléctroménager" },
      { id: 163, libelle: "Réparateur de pompe à chaleur" },
      { id: 164, libelle: "Réparateur et traiteur d'humidité" },
      { id: 165, libelle: "Réparateur Toiture " },
      { id: 166, libelle: "Sableur" },
      { id: 167, libelle: "Scieur " },
      { id: 168, libelle: "Sérrurier" },
      { id: 169, libelle: "Solier" },
      { id: 170, libelle: "Sollier Moquetiste" },
      { id: 171, libelle: "Sondeur" },
      { id: 172, libelle: "Soudeur" },
      { id: 173, libelle: "Staffeur " },
      { id: 174, libelle: "Stucateur" },
      { id: 175, libelle: "Tailleur de Pierre" },
      { id: 176, libelle: "Technicien d'équipements Piscine" },
      { id: 177, libelle: "Technicien de Maintenance" },
      { id: 178, libelle: "Technicien et Traitement de l'air" },
      { id: 179, libelle: "Technicien et Traitement de l'eau" },
      { id: 180, libelle: "Technicien et Traitement des Sols" },
      { id: 181, libelle: "Technicien et Traitement des termites" },
      { id: 182, libelle: "Technicien Planchers" },
      { id: 183, libelle: "Technicien Réseau Internet" },
      { id: 184, libelle: "Technicien Réseau téléphonique" },
      { id: 185, libelle: "Terrasseur" },
      { id: 186, libelle: "Topographe" },
      { id: 187, libelle: "Treillageur" },
      { id: 188, libelle: "Vendeur - Commercant " },
      { id: 189, libelle: "Vendeur de Carrelage" },
      { id: 190, libelle: "Vendeur de Ciment" },
      { id: 191, libelle: "Vendeur de Matériaux" },
      { id: 192, libelle: "Ventiliste" },
      { id: 193, libelle: "Viabilisateur" },
      { id: 194, libelle: "Vidangeur" },
      { id: 195, libelle: "Vitrier" },
      { id: 196, libelle: "Zingueur" },
      { id: 197, libelle: "Conseiller en prêt immobilier" },
      { id: 198, libelle: "Poseur" },
      { id: 199, libelle: "Poseur de Borne" },
      { id: 200, libelle: "Gestionnaire Locatif" },
      { id: 201, libelle: "Gestionnaire d'actifs immobilier" },
      { id: 202, libelle: "Chef de chantier" },
      { id: 203, libelle: "Mairie" },
      { id: 204, libelle: "Huissier de justice" },
      { id: 205, libelle: "Agent d'état des lieux" },
      { id: 206, libelle: "Commercial" },
      { id: 207, libelle: "Entreprise Abatatage, elagage, defrichage" },
      { id: 208, libelle: "Monteur et Installeur de Hammam" },
      { id: 209, libelle: "Association" },
      { id: 210, libelle: "Laveur Auto/voiture à domicile" },
    ];

    for (const metier of metiersData) {
      const createdMetier = await prisma.metier.create({
        data: {libelle:metier.libelle},
      });
      console.log(`➕ Métier : ${metier.libelle} créé`);
    }

    console.log("🌿 Seeding terminé avec succès !");
  } catch (error) {
    console.error("❌ Erreur lors de la création des donnes:", error);
  } finally {
    await prisma.$disconnect();
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
